# Women's Intimates Pricing
## Exploratory Data Analysis

The data sets I have pulled in to explore are from nine different women's intimates brands. Each brand has their own CSV file; the columns are consistent across multiple CSVs. My goal is to combine all of the separated data sets in to one dataframe to work from.

### Importing Libraries and Combining All Data Sets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
import os
import glob

#Setting working directory to folder where all CSVs are located
os.chdir('./data')

In [3]:
#Matching the csv pattern and saving all file names in to a single variable
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [4]:
#Combining all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])

#Exporting to a csv
combined_csv.to_csv('combined_data.csv', index=False, encoding='utf-8-sig')

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3249: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):


In [5]:
#Confirming I'm still working in the correct directory
!pwd

/Users/ashleystacey/GA_DS/Final_Project/data


In [6]:
#Reading in the new combined CSV as a dataframe
df = pd.read_csv('combined_data.csv')

df.head()

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


product_name        mrp      price  \
0  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
1  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
2  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
3  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
4  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
1  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
2  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
3  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
4  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color  
0  Rugged Green  
1  Natural Nude  
2    True Black  
3         White  
4    Royal Navy

In [7]:
df.retailer.unique()

array(['Ae US', 'Hankypanky US', 'Calvin Klein US', 'Macys US',
       'Amazon US', 'Btemptd US', 'Topshop US', 'Nordstrom US',
       'Victoriassecret US'], dtype=object)

In [8]:
df.shape

(4797592, 14)

In [9]:
df[df['brand_name'] == 'HankyPanky'].shape

(315045, 14)

In [10]:
2958163 - 210030

2748133

In [11]:
df.describe()

rating  review_count
count  1.891660e+06  1.787926e+06
mean   4.261966e+00  5.671599e+35
std    5.336998e-01  9.140368e+36
min    0.000000e+00  1.000000e+00
25%    4.000000e+00  1.300000e+01
50%    4.300000e+00  9.200000e+01
75%    4.500000e+00  3.850000e+02
max    5.000000e+00  1.560000e+38

In [12]:
df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

### Investigating Currency

I noted above that the price and mrp columns are set to type object. One of these will be my target and is meant to be a continuous variable in US dollars. Below I will begin digging in to the column to determine what needs to be changed.

In [13]:
#Subsetting my data frame so I can check if all observations are in USD for mrp
usd_mrp_check = df[df.mrp.str.contains('USD')]
usd_mrp_check.shape

(254952, 14)

Not all rows have "USD"...are we looking at multiple currencies?

In [14]:
#Creating a list of unique values in the mrp column
mrp_values = list(df.mrp.unique())

In [15]:
print(mrp_values)

['12.50 USD', '9.50 USD', '7.50 USD', '14.50 USD', '49.95 USD', '44.95 USD', '29.95 USD', '22.95 USD', '39.95 USD', '26.95 USD', '69.99 USD', '24.95 USD', '32.95 USD', '34.95 USD', '36.95 USD', '72.99 USD', '66.99 USD', '15.50 USD', '38.50 USD', '11.50 USD', '36.50 USD', '$68 ', '$30 ', '$59 ', '$615 ', '$64 ', '$86 ', '$60 ', '$23 ', '$82 ', '$90 ', '$34 ', '$96 ', '$39 ', '$41 ', '$49 ', '$58 ', '$32 ', '$102 ', '$92 ', '$50 ', '$69 ', '$140 ', '$53 ', '$24 ', '$56 ', '$160 ', '$25 ', '$126 ', '$20 ', '$48 ', '$62 ', '$22 ', '$54 ', '$36 ', '$15 ', '$35 ', '$28 ', '$14 ', '$47 ', '$110 ', '$78 ', '$52 ', '$67 ', '$72 ', '$79 ', '$70 ', '$44 ', '$29 ', '$42 ', '$128 ', '$83 ', '$108 ', '$40 ', '$38 ', '$75 ', '$158 ', '$186 ', '$106 ', '$94 ', '$135 ', '$57 ', '$89 ', '$85 ', '$27 ', '$32.50 ', '$46 ', '$18 ', '$10 ', '$80 ', '$84 ', '$19 ', '$112 ', '$98 ', '$63 ', '$74 ', '$66 ', '$26 ', '$55 ', '$21 ', '$118 ', '$116 ', '$11 ', '$100 ', '$165 ', '$43 ', '$125 ', '$12 ', '$295 ', '$

These will need to be stripped down and turned in to floats. My hunch is that each brand

I may need to look at each dataset individually and clean them; the mrp unique values list leads me to believe that each brand has different formatting, so I may need to go back to each individual CSV to do my cleaning before combining them again.

## Investigating Null Values

In [16]:
#Creating a dataframe to see the count of null values in each column
null_count_df = df.isnull().sum().rename_axis('cols').reset_index(name='null_counts')
null_count_df

cols  null_counts
0       product_name            0
1                mrp            0
2              price            0
3            pdp_url            0
4         brand_name            0
5   product_category            0
6           retailer            0
7        description            0
8             rating      2905932
9       review_count      3009666
10  style_attributes      3400085
11       total_sizes            0
12    available_size            0
13             color         5416

In [17]:
#Creating a percent to total column to see how many observations are null out of all observations
null_count_df['pct_ttl'] = null_count_df['null_counts']/613143

In [18]:
null_count_df

cols  null_counts   pct_ttl
0       product_name            0  0.000000
1                mrp            0  0.000000
2              price            0  0.000000
3            pdp_url            0  0.000000
4         brand_name            0  0.000000
5   product_category            0  0.000000
6           retailer            0  0.000000
7        description            0  0.000000
8             rating      2905932  4.739403
9       review_count      3009666  4.908587
10  style_attributes      3400085  5.545338
11       total_sizes            0  0.000000
12    available_size            0  0.000000
13             color         5416  0.008833

The majority of review_count and rating are null values. I'm not sure I want to drop them just yet because I may be able to assign a review_count for duplicate styles if any exist.

## Cleaning by Brand

This will be a more onerous process to get each CSV cleaned the way it needs to be. For the sake of time, I've included the process of cleaning one of my sets as an example. I will complete the rest and have a more robust Jupyter Notebook for the Final due date, I just know roughly 80% of this project will ultimately be cleaning these datasets.

### Aerie (AE)

In [19]:
#Reading in the Aerie dataset in to its own dataframe. Once I have cleaned this up, I will save as a new cleaned CSV file for combination with all sets later
ae_df = pd.read_csv('ae_com.csv')
ae_df.head()

product_name        mrp      price  \
0  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
1  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
2  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
3  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   
4  Aerie Everyday Loves Lace Cheeky  12.50 USD  12.50 USD   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
1  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
2  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
3  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
4  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color  
0  Rugged Green  
1  Natural Nude  
2    True Black  
3         White  
4    Royal Navy

In [20]:
#Creating a list of mrp's unique values
ae_mrp_list = list(ae_df.mrp.unique())
print(ae_mrp_list)

['12.50 USD', '9.50 USD', '7.50 USD', '14.50 USD', '49.95 USD', '44.95 USD', '29.95 USD', '22.95 USD', '39.95 USD', '26.95 USD', '69.99 USD', '24.95 USD', '32.95 USD', '34.95 USD', '36.95 USD', '72.99 USD', '66.99 USD', '15.50 USD', '38.50 USD', '11.50 USD', '36.50 USD']


In [21]:
#Stripping 'USD' from the values. These are otherwise ready to convert to floats.
ae_df.mrp = ae_df.mrp.str.strip('USD')

In [22]:
#Creating a list of price's unique values
ae_price_list = list(ae_df.price.unique())
print(ae_price_list)

['12.50 USD', '9.50 USD', '7.50 USD', '14.50 USD', '34.96 USD', '31.46 USD', '20.96 USD', '16.06 USD', '27.96 USD', '18.86 USD', '48.99 USD', '17.46 USD', '23.06 USD', '24.46 USD', '25.86 USD', '51.09 USD', '10.15 USD', '46.89 USD', '10.85 USD', '26.95 USD', '8.05 USD', '25.55 USD', '26.97 USD', '23.97 USD', '22.47 USD', '17.47 USD', '29.97 USD', '14.97 USD', '13.47 USD', '20.97 USD', '17.97 USD', '24.97 USD', '11.47 USD', '12.47 USD', '19.77 USD', '22.17 USD', '19.97 USD', '3.99 USD', '16.17 USD', '13.77 USD', '13.98 USD', '17.98 USD']


In [23]:
#Stripping 'USD' from the values
ae_df.price = ae_df.price.str.strip('USD')
ae_df.head()

product_name     mrp   price  \
0  Aerie Everyday Loves Lace Cheeky  12.50   12.50    
1  Aerie Everyday Loves Lace Cheeky  12.50   12.50    
2  Aerie Everyday Loves Lace Cheeky  12.50   12.50    
3  Aerie Everyday Loves Lace Cheeky  12.50   12.50    
4  Aerie Everyday Loves Lace Cheeky  12.50   12.50    

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
1  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
2  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
3  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
4  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color  
0  Rugged Green  
1  Natural Nude  
2    True Black  
3         White  
4    Royal Navy

In [24]:
ae_df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

The price and mrp data types are still set to object and need to be converted to numbers.

In [25]:
#Changing data types to floats
ae_df.mrp = ae_df.mrp.astype(float)
ae_df.price = ae_df.price.astype(float)
ae_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [26]:
ae_df.head()

product_name   mrp  price  \
0  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
1  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
2  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
3  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
4  Aerie Everyday Loves Lace Cheeky  12.5   12.5   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
1  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
2  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
3  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
4  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color  
0  Rugged Green  
1  Natural Nude  
2    True Black  
3         White  
4    Royal Navy

In [27]:
#Checking null values
ae_df.isnull().sum()

product_name            0
mrp                     0
price                   0
pdp_url                 0
brand_name              0
product_category        0
retailer                0
description             0
rating               7203
review_count        18738
style_attributes        0
total_sizes             0
available_size          0
color                   0
dtype: int64

In [28]:
ae_df.shape

(28328, 14)

In [29]:
ae_df.describe()

mrp         price        rating  review_count
count  28328.000000  28328.000000  21125.000000   9590.000000
mean      22.822207     16.213737      4.276251      7.862148
std       13.026553      7.052662      0.736672     15.736077
min        7.500000      3.990000      1.000000      1.000000
25%       11.500000      9.500000      4.000000      1.000000
50%       22.950000     13.470000      4.400000      3.000000
75%       29.950000     19.770000      4.800000      6.000000
max       72.990000     51.090000      5.000000     92.000000

Aerie has an interesting range of MRP. MRP is essentially the suggested retailer price or ticket price. The actual price in the price column is the price the product was being promoted at at the time the data was pulled. Given that American Eagle (the parent to Aerie) is a fairly promotional brand, I'm not surprised that the prices and MRPs differ. Specialty retailers set an initial markup price (MRP/SRP/etc.) to start with a profitable margin compared to cost that allows the flexibility of the brand's promotional cadence.

In [30]:
#Checking rows where the review count is null
ae_df[ae_df.review_count.isnull()]

product_name    mrp  price  \
6           Aerie Lace Hi-Rise Boybrief  12.50  12.50   
7           Aerie Lace Hi-Rise Boybrief  12.50  12.50   
8           Aerie Lace Hi-Rise Boybrief  12.50  12.50   
9           Aerie Lace Hi-Rise Boybrief  12.50  12.50   
10          Aerie Lace Hi-Rise Boybrief  12.50  12.50   
...                                 ...    ...    ...   
28323  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28324  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28325  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28326  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28327  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   

                                                 pdp_url brand_name  \
6      https://www.ae.com/undies-aerie-lace-hi-rise-b...      AERIE   
7      https://www.ae.com/undies-aerie-lace-hi-rise-b...      AERIE   
8      https://www.ae.com/undies-aerie-lace-hi-rise-b...      AERIE   
9      https://www.ae.com/undies-aerie-lace-hi-rise-b...      AERIE   
10     https://www.ae.com/undies-aerie-lace-hi-rise-b...      AERIE   
...                                                  ...        ...   
28323  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28324  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28325  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28326  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28327  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   

      product_category retailer  \
6            Boybriefs    Ae US   
7            Boybriefs    Ae US   
8            Boybriefs    Ae US   
9            Boybriefs    Ae US   
10           Boybriefs    Ae US   
...                ...      ...   
28323        Bralettes    Ae US   
28324        Bralettes    Ae US   
28325        Bralettes    Ae US   
28326        Bralettes    Ae US   
28327        Bralettes    Ae US   

                                             description  rating  \
6      Laced with love and extra comfort. No cheek pe...     4.8   
7      Laced with love and extra comfort. No cheek pe...     4.8   
8      Laced with love and extra comfort. No cheek pe...     4.8   
9      Laced with love and extra comfort. No cheek pe...     4.8   
10     Laced with love and extra comfort. No cheek pe...     4.8   
...                                                  ...     ...   
28323  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28324  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28325  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28326  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28327  ¡Amor! New bralettes. Get bralette happy. This...     NaN   

       review_count                                   style_attributes  \
6               NaN  ["Soft lace with the right amount of stretch",...   
7               NaN  ["Soft lace with the right amount of stretch",...   
8               NaN  ["Soft lace with the right amount of stretch",...   
9               NaN  ["Soft lace with the right amount of stretch",...   
10              NaN  ["Soft lace with the right amount of stretch",...   
...             ...                                                ...   
28323           NaN  ["Shine fabric + guipure lace trim", "Crop sil...   
28324           NaN  ["Shine fabric + guipure lace trim", "Crop sil...   
28325           NaN  ["Shine fabric + guipure lace trim", "Crop sil...   
28326           NaN  ["Shine fabric + guipure lace trim", "Crop sil...   
28327           NaN  ["Shine fabric + guipure lace trim", "Crop sil...   

                              total_sizes               available_size  \
6      ["XS", "S", "M", "L", "XL", "XXL"]        ["XS", "S", "M", "L"]   
7      ["XS", "S", "M", "L", "XL", "XXL"]             ["XS", "S", "M"]   
8      ["XS", "S", "M", "L", "XL", "XXL"]                  ["XS", "S"]   
9      ["XS", "S", "M", "L", "XL", "XXL"]             ["XS", "S", 

Interestingly, there are a number of products that have been reviewed numerically but don't have a written review available for the style.

In [31]:
ae_df.review_count.unique()

array([ 8., nan, 11., 10.,  2.,  6.,  1.,  7.,  4., 32.,  5.,  3., 14.,
       18., 12., 13.,  9., 26., 15., 29., 92., 63.])

In [32]:
ae_df.rating.unique()

array([5. , 4.8, 4.7, 4. , nan, 3.3, 4.5, 4.6, 3.8, 2. , 3.6, 4.4, 1. ,
       4.2, 3. , 4.3, 3.5, 2.9, 2.8, 4.1, 3.7, 3.4, 3.9, 3.1, 4.9, 2.4,
       3.2, 1.5, 2.5, 2.1, 2.3, 2.2, 2.6])

Given that all of the data points are from the eCommerce arm of the brands represented, as long as 0 isn't represented in the review_count it would make sense that nulls = 0.

In [33]:
#Filling review_count nulls with 0
ae_df.review_count.fillna(0, inplace=True)

In [34]:
#Changing review count values to integers. Review counts are whole numbers, they aren't averaging out the number of reviews for each product
ae_df.review_count = ae_df.review_count.astype(int)
ae_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count          int64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [35]:
#Gut check that these were successfully changed
ae_df.review_count.unique()

array([ 8,  0, 11, 10,  2,  6,  1,  7,  4, 32,  5,  3, 14, 18, 12, 13,  9,
       26, 15, 29, 92, 63])

In [36]:
ae_df.head()

product_name   mrp  price  \
0  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
1  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
2  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
3  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
4  Aerie Everyday Loves Lace Cheeky  12.5   12.5   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0             8   
1  Introducing Everyday Loves™: Made with love. E...     5.0             8   
2  Introducing Everyday Loves™: Made with love. E...     5.0             8   
3  Introducing Everyday Loves™: Made with love. E...     5.0             8   
4  Introducing Everyday Loves™: Made with love. E...     5.0             8   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color  
0  Rugged Green  
1  Natural Nude  
2    True Black  
3         White  
4    Royal Navy

In [37]:
#Checking null values
ae_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              7203
review_count           0
style_attributes       0
total_sizes            0
available_size         0
color                  0
dtype: int64

Rating has plenty of null values. I'm toying with the idea of filling these nulls with the average rating based on product category. Null values of the actual reviews does not equal 0; it means that the product has yet to be reviewed, possibly because it is too new to have been purchased. I think it's logical to assume that product categories have similar reviews.

In [38]:
#Checking averages grouped by product_category
ae_df.groupby(['product_category']).mean()

mrp      price    rating  \
product_category                                                         
Audrey                                  37.992105  25.919684  3.737349   
Bandeau                                 24.175806  14.463226  4.547368   
Bikinis                                 10.327957  10.327957  4.466120   
Boybrief                                14.500000  14.500000  4.446154   
Boybriefs                               11.014312  11.006801  4.448440   
Boyshorts                               11.089623  11.089623  4.423077   
Bra Accessories                         27.049550  18.934685  3.355172   
Bralettes                               27.379336  16.169385  4.228932   
Bras                                    42.920123  28.120685  4.196008   
Bridget                                 32.750866  22.007835  3.777064   
Brooke                                  39.541837  26.422347  2.691304   
Cheekies                                10.572054  10.572054  4.941070   
Chill                                   34.950000  20.241368  4.294167   
Classic                                 28.139802  16.444731  4.224415   
Everyday Loves Undies 6 for $26 USD     10.755738  10.755738  4.468852   
Everyday Loves Undies 7 for $27.50 USD  10.770661  10.770661  4.595018   
Halter                                  26.272148  15.726812  4.207463   
Hannah                                  32.492105  21.860632  4.163187   
HiLeg Bikinis                            9.500000   9.500000  4.006667   
HiNeck                                  34.950000  20.970000  4.550000   
HiRise Boybriefs                        12.500000  12.500000  4.987500   
Katie                                   32.293750  21.771172  3.937500   
Lightly Lined Bras                      38.374558  25.772706  4.168030   
Longline                                28.288259  15.661429  4.258206   
Lorna Jane                              70.624615  49.434231  5.000000   
Move                                    49.950000  30.854668  3.316928   
New! Bandeau                            26.950000  16.349080  4.662992   
New! Day To Play                        47.727778  31.817500  3.101000   
New! Sunnie Bandeau                     32.154724  19.156299  3.685981   
Padded                                  27.578049  16.604329  3.612500   
Play                                    40.116667  24.320111  4.454237   
Plunge                                  29.131818  17.737844  4.171875   
Pushup Bras                             42.300120  28.422266  3.645248   
Racerback                               27.075632  15.713668  4.186500   
Sports Bras                             41.799345  25.127548  3.934174   
Strapless Bras                          31.439048  20.200921  3.852045   
Summer                                  42.046774  28.438226  3.074194   
Sunnie Demi                             42.785052  28.658918  4.060825   
Sunnie Full Coverage                    43.093460  28.802869  4.348261   
Sunnie Pushup                           48.030986  32.183063  4.228251   
Sunnie Undies $5 USD                    14.500000  14.500000  4.365986   
Sunnie Undies 3 for $26 USD             14.500000  14.500000  4.376344   
Sunnie Wireless                         39.950000  26.795036  4.533871   
Thong                                   14.500000  14.500000  4.288889   
Thongs                                  11.226975  11.179499  4.517355   
Tomgirl                                 29.950000  17.967037  4.979167   
Triangle                                27.532305  16.621770  3.972480   
Undies                                  14.500000  14.500000  4.363333   
Unlined Bras                            29.871053  17.928169  4.185714   

                                        review_count  
product_category                                      
Audrey                                      0.136842  
Bandeau                                     1.209677  
Bikinis                                     1.04659

This actually lead me to discover that there are potentially some duplicates that could be grouped under a parent category. Bras and undies will still be kept separate even if they are a part of the same collection, but something like "Sunnie Undies $5 USD" and "Sunnie Undies 3 for $26 USD" can be assigned under a "Sunnie Undies" parent category.

In [39]:
ae_df[ae_df['product_category'] == 'Triangle'].product_name.unique()

array(['Aerie Classic Lace Bralette',
       'Aerie Padded Romantic Lace Bralette', "Happy Rockin' Unlined Bra",
       'Aerie Triangle Bralette + Embroidery',
       'Aerie Triangle Lace Trim Bralette',
       'Aerie Padded Printed Bralette'], dtype=object)

In [40]:
#Creating a dictionary for parent category
parent_dict = {'Audrey':'Bras',
               'Bandeau':'Bras',
               'Bikinis':'Panties',
               'Boybrief':'Panties',
               'Boybriefs':'Panties',
               'Cheekies':'Panties',
               'Chill':'Bras',
               'Classic':'Bras',
               'Everyday Loves Undies 6 for $26 USD':'Panties',
               'Everyday Loves Undies 7 for $27.50 USD':'Panties',
               'Halter':'Bras',
               'Hannah':'Bras',
               'HiLeg Bikinis':'Panties',
               'HiNeck':'Bras',
               'HiRise Boybriefs':'Panties',
               'Katie':'Bras',
               'Lightly Lined Bras':'Bras',
               'Longline':'Bras',
               'Lorna Jane':'Bras',
               'Move':'Bras',
               'New! Bandeau':'Bras',
               'New! Day To Play':'Bras',
               'New! Sunnie Bandeau':'Bras',
               'Padded':'Bras',
               'Play':'Bras',
               'Plunge':'Bras',
               'Pushup Bras':'Bras',
               'Racerback':'Bras',
               'Sports Bras':'Bras',
               'Strapless Bras':'Bras',
               'Summer':'Bras',
               'Sunnie Demi':'Bras',
               'Sunnie Full Coverage':'Bras',
               'Sunnie Pushup':'Bras',
               'Sunnie Undies $5 USD':'Panties',
               'Sunnie Undies 3 for $26 USD':'Panties',
               'Sunnie Wireless':'Bras',
               'Thong':'Panties',
               'Thongs':'Panties',
               'Tomgirl':'Bras',
               'Triangle':'Bras',
               'Undies':'Panties',
               'Unlined Bras':'Bras'
              }

In [41]:
#Mapping the parent category dictionary to the values in product_category to create a new column, parent_category
ae_df['parent_category'] = ae_df.product_category.map(parent_dict)

In [42]:
ae_df.head()

product_name   mrp  price  \
0  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
1  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
2  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
3  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
4  Aerie Everyday Loves Lace Cheeky  12.5   12.5   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0             8   
1  Introducing Everyday Loves™: Made with love. E...     5.0             8   
2  Introducing Everyday Loves™: Made with love. E...     5.0             8   
3  Introducing Everyday Loves™: Made with love. E...     5.0             8   
4  Introducing Everyday Loves™: Made with love. E...     5.0             8   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color parent_category  
0  Rugged Green         Panties  
1  Natural Nude         Panties  
2    True Black         Panties  
3         White         Panties  
4    Royal Navy         Panties

In [43]:
ae_df.groupby(['parent_category']).mean()

mrp      price    rating  review_count
parent_category                                              
Bras             34.800489  21.668450  4.061480      3.057609
Panties          11.042694  11.033523  4.556989      2.945670

In [44]:
ae_df[ae_df.rating.isnull()]

product_name    mrp  price  \
21       Aerie Shine Bikini + Boho Lace  12.50  12.50   
22       Aerie Shine Bikini + Boho Lace  12.50  12.50   
23       Aerie Shine Bikini + Boho Lace  12.50  12.50   
27         Aerie Lace Back String Thong   7.50   7.50   
28                         Aerie Bikini   9.50   9.50   
...                                 ...    ...    ...   
28323  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28324  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28325  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28326  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28327  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   

                                                 pdp_url brand_name  \
21     https://www.ae.com/undies-aerie-shine-bikini-b...      AERIE   
22     https://www.ae.com/undies-aerie-shine-bikini-b...      AERIE   
23     https://www.ae.com/undies-aerie-shine-bikini-b...      AERIE   
27     https://www.ae.com/undies-aerie-lace-back-stri...      AERIE   
28     https://www.ae.com/undies-aerie-bikini-buff/ae...      AERIE   
...                                                  ...        ...   
28323  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28324  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28325  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28326  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28327  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   

      product_category retailer  \
21             Bikinis    Ae US   
22             Bikinis    Ae US   
23             Bikinis    Ae US   
27              Thongs    Ae US   
28             Bikinis    Ae US   
...                ...      ...   
28323        Bralettes    Ae US   
28324        Bralettes    Ae US   
28325        Bralettes    Ae US   
28326        Bralettes    Ae US   
28327        Bralettes    Ae US   

                                             description  rating  \
21     Shine on. A peek of cheek meets peace, love an...     NaN   
22     Shine on. A peek of cheek meets peace, love an...     NaN   
23     Shine on. A peek of cheek meets peace, love an...     NaN   
27     NO PANTS PARTY! Gettin’ stringy with it… style...     NaN   
28     Introducing Everyday Loves™: Made with love. E...     NaN   
...                                                  ...     ...   
28323  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28324  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28325  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28326  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28327  ¡Amor! New bralettes. Get bralette happy. This...     NaN   

       review_count                                   style_attributes  \
21                0  ["Smooth shine fabric + Boho lace", "Aerie und...   
22                0  ["Smooth shine fabric + Boho lace", "Aerie und...   
23                0  ["Smooth shine fabric + Boho lace", "Aerie und...   
27                0  ["Comfy, stretchy cotton", "Low rise", "Total ...   
28                0  ["Comfy, stretchy cotton", "Panties, underwear...   
...             ...                                                ...   
28323             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28324             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28325             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28326             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28327             0  ["Shine fabric + guipure lace trim", "Crop sil...   

                                     total_sizes  \
21            ["XS", "S", "M", "L", "XL", "XXL"]   
22            ["XS", "S", "M", "L", "XL", "XXL"]   
23            ["XS", "S", "M", "L", "XL", "XXL"]   
27     ["XXS", "XS", "S", "M", "L", "XL", "XXL"]   
28            ["XS", "S", "M", "L", "XL", "XXL"]   
...                                          ...  

In [45]:
ae_df.isnull().sum()/len(ae_df)

product_name        0.000000
mrp                 0.000000
price               0.000000
pdp_url             0.000000
brand_name          0.000000
product_category    0.000000
retailer            0.000000
description         0.000000
rating              0.254271
review_count        0.000000
style_attributes    0.000000
total_sizes         0.000000
available_size      0.000000
color               0.000000
parent_category     0.137249
dtype: float64

In [46]:
ae_df.head()

product_name   mrp  price  \
0  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
1  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
2  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
3  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
4  Aerie Everyday Loves Lace Cheeky  12.5   12.5   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0             8   
1  Introducing Everyday Loves™: Made with love. E...     5.0             8   
2  Introducing Everyday Loves™: Made with love. E...     5.0             8   
3  Introducing Everyday Loves™: Made with love. E...     5.0             8   
4  Introducing Everyday Loves™: Made with love. E...     5.0             8   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color parent_category  
0  Rugged Green         Panties  
1  Natural Nude         Panties  
2    True Black         Panties  
3         White         Panties  
4    Royal Navy         Panties

In [47]:
ae_df['rating'].fillna(ae_df.parent_category.map({'Bras': 4.06, 'Panties': 4.56}))

0        5.0
1        5.0
2        5.0
3        5.0
4        5.0
        ... 
28323    NaN
28324    NaN
28325    NaN
28326    NaN
28327    NaN
Name: rating, Length: 28328, dtype: float64

In [48]:
ae_df[ae_df['parent_category'].isnull()]

product_name    mrp  price  \
44                       Aerie Boyshort   9.50   9.50   
95                       Aerie Boyshort   9.50   9.50   
96                       Aerie Boyshort   9.50   9.50   
97                       Aerie Boyshort   9.50   9.50   
107                      Aerie Boyshort   9.50   9.50   
...                                 ...    ...    ...   
28323  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28324  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28325  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28326  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   
28327  Aerie Hi-Neck Lace Trim Bralette  34.95  20.97   

                                                 pdp_url brand_name  \
44     https://www.ae.com/aerie-boyshort-dark-heather...      AERIE   
95     https://www.ae.com/featured-aerie-boyshort-dee...      AERIE   
96     https://www.ae.com/featured-aerie-boyshort-dee...      AERIE   
97     https://www.ae.com/featured-aerie-boyshort-dee...      AERIE   
107    https://www.ae.com/aerie-boyshort-true-black/a...      AERIE   
...                                                  ...        ...   
28323  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28324  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28325  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28326  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   
28327  https://www.ae.com/aerie-hi-neck-lace-trim-bra...      AERIE   

      product_category retailer  \
44           Boyshorts    Ae US   
95           Boyshorts    Ae US   
96           Boyshorts    Ae US   
97           Boyshorts    Ae US   
107          Boyshorts    Ae US   
...                ...      ...   
28323        Bralettes    Ae US   
28324        Bralettes    Ae US   
28325        Bralettes    Ae US   
28326        Bralettes    Ae US   
28327        Bralettes    Ae US   

                                             description  rating  \
44     No. 1 on our short list for a no pants party! ...     2.0   
95     Boy oh boy! The soft and comfy cotton you love...     NaN   
96     Boy oh boy! The soft and comfy cotton you love...     NaN   
97     Boy oh boy! The soft and comfy cotton you love...     NaN   
107    Boy oh boy! The soft and comfy cotton you love...     NaN   
...                                                  ...     ...   
28323  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28324  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28325  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28326  ¡Amor! New bralettes. Get bralette happy. This...     NaN   
28327  ¡Amor! New bralettes. Get bralette happy. This...     NaN   

       review_count                                   style_attributes  \
44                2  ["Comfy, stretchy cotton", "Undies: the REAL w...   
95                0  ["Comfy, stretchy cotton", "Aerie undies: Your...   
96                0  ["Comfy, stretchy cotton", "Aerie undies: Your...   
97                0  ["Comfy, stretchy cotton", "Aerie undies: Your...   
107               0  ["Comfy cotton", "Low rise", "No cheek peek", ...   
...             ...                                                ...   
28323             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28324             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28325             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28326             0  ["Shine fabric + guipure lace trim", "Crop sil...   
28327             0  ["Shine fabric + guipure lace trim", "Crop sil...   

                                     total_sizes  \
44     ["XXS", "XS", "S", "M", "L", "XL", "XXL"]   
95            ["XS", "S", "M", "L", "XL", "XXL"]   
96            ["XS", "S", "M", "L", "XL", "XXL"]   
97            ["XS", "S", "M", "L", "XL", "XXL"]   
107           ["XS", "S", "M", "L", "XL", "XXL"]   
...                                          ...  

In [49]:
ae_df[ae_df['parent_category'].isnull()].product_category.unique()

array(['Boyshorts', 'Bridget', 'Bralettes', 'Brooke', 'Bra Accessories',
       'Bras'], dtype=object)

In [50]:
null_cat_dict = {'Boyshorts':'Panties', 'Bridget':'Bras', 'Bralettes':'Bras', 'Brooke':'Bras', 'Bras':'Bras'}

In [51]:
ae_df[ae_df['product_category'] == 'Bridget']

product_name    mrp  price  \
485      Bridget Pushup Cotton Bra  32.95  23.06   
486      Bridget Pushup Cotton Bra  32.95  23.06   
487      Bridget Pushup Cotton Bra  32.95  23.06   
488      Bridget Pushup Cotton Bra  32.95  23.06   
499             Bridget Pushup Bra  29.95  20.96   
...                            ...    ...    ...   
26998           Bridget Pushup Bra  34.95  24.46   
26999           Bridget Pushup Bra  34.95  24.46   
27000           Bridget Pushup Bra  34.95  24.46   
28039  Bridget Longline Pushup Bra  34.95  24.46   
28040  Bridget Longline Pushup Bra  34.95  24.46   

                                                 pdp_url brand_name  \
485    https://www.ae.com/aerie-bridget-pushup-cotton...      AERIE   
486    https://www.ae.com/aerie-bridget-pushup-cotton...      AERIE   
487    https://www.ae.com/aerie-bridget-pushup-cotton...      AERIE   
488    https://www.ae.com/aerie-bridget-pushup-cotton...      AERIE   
499    https://www.ae.com/aerie-bridget-pushup-bra-wh...      AERIE   
...                                                  ...        ...   
26998  https://www.ae.com/aerie-bridget-pushup-bra-de...      AERIE   
26999  https://www.ae.com/aerie-bridget-pushup-bra-de...      AERIE   
27000  https://www.ae.com/aerie-bridget-pushup-bra-de...      AERIE   
28039  https://www.ae.com/aerie-bridget-longline-push...      AERIE   
28040  https://www.ae.com/aerie-bridget-longline-push...      AERIE   

      product_category retailer  \
485            Bridget    Ae US   
486            Bridget    Ae US   
487            Bridget    Ae US   
488            Bridget    Ae US   
499            Bridget    Ae US   
...                ...      ...   
26998          Bridget    Ae US   
26999          Bridget    Ae US   
27000          Bridget    Ae US   
28039          Bridget    Ae US   
28040          Bridget    Ae US   

                                             description  rating  \
485    The Flirt Everyday perkiness for every girl. s...     4.1   
486    The Flirt Everyday perkiness for every girl. s...     4.1   
487    The Flirt Everyday perkiness for every girl. s...     4.1   
488    The Flirt Everyday perkiness for every girl. s...     4.1   
499    The Flirt Everyday perkiness for every girl. s...     3.1   
...                                                  ...     ...   
26998  The Flirt Everyday perkiness for every girl. s...     5.0   
26999  The Flirt Everyday perkiness for every girl. s...     5.0   
27000  The Flirt Everyday perkiness for every girl. s...     5.0   
28039  The Flirt Everyday perkiness for every girl. s...     3.6   
28040  The Flirt Everyday perkiness for every girl. s...     3.6   

       review_count                                   style_attributes  \
485               0  ["Pushup level: Perky", "Demi coverage", "Soft...   
486               0  ["Pushup level: Perky", "Demi coverage", "Soft...   
487               0  ["Pushup level: Perky", "Demi coverage", "Soft...   
488               0  ["Pushup level: Perky", "Demi coverage", "Soft...   
499               0  ["Pushup level: Perky", "Demi coverage", "Soft...   
...             ...                                                ...   
26998             1  ["Pushup level: Perky", "Demi coverage", "Unde...   
26999             1  ["Pushup level: Perky", "Demi coverage", "Unde...   
27000             1  ["Pushup level: Perky", "Demi coverage", "Unde...   
28039             0  ["Pushup level: Perky", "Demi coverage, Longli...   
28040             0  ["Pushup level: Perky", "Demi coverage, Longli...   

                                             total_sizes  \
485    ["30A", "30B", "30C", "30D", "32AA", "32A", "3...   
486    ["30A", "30B", "30C", "30D", "32AA", "32A", "3...   
487    ["30A", "30B", "30C", "30D", "32AA", "32A", "3...   
488    ["30A", "30B", "30C", "30D", "32AA", "32A", "3...   
499    ["30A", "30B", "30C", "30D", "32AA", "32A", "3...   
...                                                  ... 

In [52]:
ae_df[ae_df['product_category'] == 'Brooke']

product_name    mrp  price  \
599              Brooke Pushup Bra  34.95  24.46   
616    Brooke Racerback Pushup Bra  39.95  27.96   
617    Brooke Racerback Pushup Bra  39.95  27.96   
618    Brooke Racerback Pushup Bra  39.95  27.96   
937    Brooke Racerback Pushup Bra  39.95  27.96   
...                            ...    ...    ...   
26250  Brooke Racerback Pushup Bra  39.95  27.96   
27184  Brooke Racerback Pushup Bra  39.95  27.96   
27185  Brooke Racerback Pushup Bra  39.95  27.96   
27628   Brooke Pushup Longline Bra  39.95  27.96   
28014            Brooke Pushup Bra  34.95  24.46   

                                                 pdp_url brand_name  \
599    https://www.ae.com/aerie-bras-brooke-pushup-br...      AERIE   
616    https://www.ae.com/aerie-brooke-racerback-push...      AERIE   
617    https://www.ae.com/aerie-brooke-racerback-push...      AERIE   
618    https://www.ae.com/aerie-brooke-racerback-push...      AERIE   
937    https://www.ae.com/aerie-brooke-racerback-push...      AERIE   
...                                                  ...        ...   
26250  https://www.ae.com/aerie-bras-brooke-racerback...      AERIE   
27184  https://www.ae.com/aerie-bras-brooke-racerback...      AERIE   
27185  https://www.ae.com/aerie-bras-brooke-racerback...      AERIE   
27628  https://www.ae.com/aerie-bras-brooke-pushup-lo...      AERIE   
28014  https://www.ae.com/aerie-bras-brooke-pushup-br...      AERIE   

      product_category retailer  \
599             Brooke    Ae US   
616             Brooke    Ae US   
617             Brooke    Ae US   
618             Brooke    Ae US   
937             Brooke    Ae US   
...                ...      ...   
26250           Brooke    Ae US   
27184           Brooke    Ae US   
27185           Brooke    Ae US   
27628           Brooke    Ae US   
28014           Brooke    Ae US   

                                             description  rating  \
599    The Bestie Your go-to pushup with just the rig...     3.0   
616    The Bestie Your go-to pushup with just the rig...     2.0   
617    The Bestie Your go-to pushup with just the rig...     2.0   
618    The Bestie Your go-to pushup with just the rig...     2.0   
937    The Bestie Your go-to pushup with just the rig...     3.5   
...                                                  ...     ...   
26250  The Bestie Your go-to pushup with just the rig...     2.5   
27184  The Bestie Your go-to pushup with just the rig...     3.5   
27185  The Bestie Your go-to pushup with just the rig...     3.5   
27628  The Bestie Your go-to pushup with just the rig...     4.5   
28014  The Bestie Your go-to pushup with just the rig...     3.3   

       review_count                                   style_attributes  \
599               0  ["Pushup level: Perkier", "Plunge silhouette",...   
616               2  ["Pushup level: Perkier", "Underwire", "Racerb...   
617               2  ["Pushup level: Perkier", "Underwire", "Racerb...   
618               2  ["Pushup level: Perkier", "Underwire", "Racerb...   
937              14  ["Pushup level: Perkier", "Underwire", "If you...   
...             ...                                                ...   
26250             0  ["Pushup level: Perky", "Plunge silhouette", "...   
27184             0  ["Pushup level: Perkier", "Plunge silhouette",...   
27185             0  ["Pushup level: Perkier", "Plunge silhouette",...   
27628             2  ["Pushup level: Perkier", "Plunge silhouette",...   
28014             0  ["Pushup level: Perkier", "Plunge silhouette",...   

                                             total_sizes  \
599    ["32A", "32B", "32C", "32D", "32DD", "32DDD", ...   
616    ["32A", "32B", "32C", "32D", "32DD", "34A", "3...   
617    ["32A", "32B", "32C", "32D", "32DD", "34A", "3...   
618    ["32A", "32B", "32C", "32D", "32DD", "34A", "3...   
937    ["32A", "32B", "32C", "32D", "32DD", "32DDD", ...   
...                                                  ... 

In [53]:
ae_df.loc[ae_df['parent_category'].isnull(),'parent_category'] = ae_df['product_category'].map(null_cat_dict)

In [54]:
ae_df[ae_df['parent_category'].isnull()]

product_name   mrp  price  \
788                    Aerie Gel Petals  14.5  10.15   
878     Aerie Adjustable Low-Back Strap  15.5  10.85   
977      Aerie Backless Pushup Bare Bra  38.5  26.95   
980    Aerie Backless U Plunge Bare Bra  38.5  26.95   
1139              Aerie Strap Converter  11.5   8.05   
...                                 ...   ...    ...   
26869                  Aerie Gel Petals  14.5  10.15   
27988    Aerie Backless Pushup Bare Bra  38.5  26.95   
27993                  Aerie Gel Petals  14.5  10.15   
28032   Aerie Adjustable Low-Back Strap  15.5  10.85   
28274           Aerie Backless Bare Bra  36.5  25.55   

                                                 pdp_url brand_name  \
788    https://www.ae.com/bras-aerie-gel-petals-cryst...      AERIE   
878    https://www.ae.com/aerie-adjustable-low-back-s...      AERIE   
977    https://www.ae.com/aerie-backless-pushup-bare-...      AERIE   
980    https://www.ae.com/aerie-backless-u-plunge-bar...      AERIE   
1139   https://www.ae.com/bras-aerie-strap-converter-...      AERIE   
...                                                  ...        ...   
26869  https://www.ae.com/bras-aerie-gel-petals-cryst...      AERIE   
27988  https://www.ae.com/aerie-backless-pushup-bare-...      AERIE   
27993  https://www.ae.com/bras-aerie-gel-petals-cryst...      AERIE   
28032  https://www.ae.com/aerie-adjustable-low-back-s...      AERIE   
28274  https://www.ae.com/bras-aerie-backless-bare-br...      AERIE   

      product_category retailer  \
788    Bra Accessories    Ae US   
878    Bra Accessories    Ae US   
977    Bra Accessories    Ae US   
980    Bra Accessories    Ae US   
1139   Bra Accessories    Ae US   
...                ...      ...   
26869  Bra Accessories    Ae US   
27988  Bra Accessories    Ae US   
27993  Bra Accessories    Ae US   
28032  Bra Accessories    Ae US   
28274  Bra Accessories    Ae US   

                                             description  rating  \
788    Quick Fixes® Collection: Endless options for e...     4.2   
878    Quick Fixes® Collection: Endless options for e...     3.0   
977    Quick Fixes® Collection: Endless options for e...     NaN   
980    Quick Fixes® Collection: Endless options for e...     3.3   
1139   Quick Fixes® Collection: Endless options for e...     NaN   
...                                                  ...     ...   
26869  Quick Fixes® Collection: Endless options for e...     4.0   
27988  Quick Fixes® Collection: Endless options for e...     NaN   
27993  Quick Fixes® Collection: Endless options for e...     4.0   
28032  Quick Fixes® Collection: Endless options for e...     4.0   
28274  Quick Fixes® Collection: Endless options for e...     5.0   

       review_count                                   style_attributes  \
788               0  ["Includes one pair", "Storage case included",...   
878               1  ["2 sets of straps included: 1 nude, 1 black",...   
977               0  ["Pushup level: Perkier", "Complete wear and c...   
980               4  ["Pushup level: Perkier", "Can be worn up to 2...   
1139              0  ["Includes 3 pieces: black, nude & clear", "Co...   
...             ...                                                ...   
26869             0  ["Includes one pair", "Storage case included",...   
27988             0  ["Pushup level: Perkier", "Backless & straples...   
27993             0  ["Includes one pair", "Storage case included",...   
28032             0  ["2 sets of straps included: 1 nude, 1 black",...   
28274             0  ["Lightly lined", "Backless & strapless", "Adh...   

                total_sizes        available_size      color parent_category  
788            ["One Size"]          ["One Size"]    Crystal             NaN  
878            ["One Size"]          ["One Size"]      Multi             NaN  
977    ["A", "B", "C", "D"]  ["A", "B", "C", "D"]  Dark Nude             NaN  
980    ["A", "B", "C", "D"]  ["A", "B", "C", "D"]  Dark Nu

In [55]:
ae_df.drop(ae_df[ae_df.product_category == 'Bra Accessories'].index, inplace=True)

In [56]:
ae_df.parent_category.isnull().sum()

0

In [57]:
ae_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              7179
review_count           0
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

In [58]:
ae_df.groupby(['parent_category']).mean()

mrp      price    rating  review_count
parent_category                                              
Bras             33.969155  21.107604  4.077321      2.514990
Panties          11.044866  11.036120  4.553298      2.834437

In [59]:
rating_dict = {'Bras':4.1, 'Panties':4.6}

ae_df.loc[ae_df['rating'].isnull(),'rating'] = ae_df['parent_category'].map(rating_dict)

In [60]:
ae_df.isnull().sum()

product_name        0
mrp                 0
price               0
pdp_url             0
brand_name          0
product_category    0
retailer            0
description         0
rating              0
review_count        0
style_attributes    0
total_sizes         0
available_size      0
color               0
parent_category     0
dtype: int64

### Amazon

In [61]:
amz_df = pd.read_csv('amazon_com.csv')
amz_df.head()

product_name      mrp    price  \
0  Calvin Klein Women's Sheer Marquisette Demi Un...  $36.00   $32.40    
1                   Wacoal Embrace Lace Bikini Panty  $27.00   $27.00    
2     Wacoal Women's Slimline Seamless Minimizer Bra  $65.00   $65.00    
3     Hanky Panky Womens Signature Lace Retro V-Kini  $36.00   $36.00    
4            Wacoal Women's Red Carpet Strapless Bra  $65.00   $65.00    

                                             pdp_url    brand_name  \
0  https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1  https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   
2  https://www.amazon.com/-/dp/B000T3606Q?th=1&psc=1        Wacoal   
3  https://www.amazon.com/-/dp/B003Y6AX0Y?th=1&psc=1   Hanky-Panky   
4  https://www.amazon.com/-/dp/B01CEBGQA0?th=1&psc=1        Wacoal   

  product_category   retailer  \
0             Bras  Amazon US   
1          Panties  Amazon US   
2             Bras  Amazon US   
3          Panties  Amazon US   
4             Bras  Amazon US   

                                         description  rating  review_count  \
0  An unlined demi cup bra featuring sheer, sexy ...     4.5            47   
1  Embrace lace bikini offers great fit and match...     4.4            91   
2  Seamless underwire minimizer bra gives great s...     4.3           298   
3  All-day comfort describes this figure-flatteri...     4.4            46   
4  Red Carpet full figure strapless fits great, s...     4.4           747   

                                    style_attributes  \
0  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   
2  [ Cups: 100% Polyester; Back: 71% Nylon, 29% S...   
3  [ Made in USA , All-day comfort describes this...   
4  [ 91% Nylon, 9% Spandex , Imported , hook and ...   

                                         total_sizes  \
0  30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...   
1                   Small , Medium , Large , X-Large   
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...   
3                   Small , Medium , Large , X-Large   
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...   

                                      available_size  color  
0  30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...   Bare  
1                           Small , Medium , X-Large  Large  
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...  Black  
3                           Small , Medium , X-Large  Large  
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...  Pecan

In [62]:
amz_df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count          int64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [63]:
amz_df.product_category.unique()

array(['Bras', 'Panties'], dtype=object)

In [64]:
amz_df.assign(parent_category = amz_df['product_category'], inplace=True)

product_name      mrp    price  \
0      Calvin Klein Women's Sheer Marquisette Demi Un...  $36.00   $32.40    
1                       Wacoal Embrace Lace Bikini Panty  $27.00   $27.00    
2         Wacoal Women's Slimline Seamless Minimizer Bra  $65.00   $65.00    
3         Hanky Panky Womens Signature Lace Retro V-Kini  $36.00   $36.00    
4                Wacoal Women's Red Carpet Strapless Bra  $65.00   $65.00    
...                                                  ...      ...      ...   
31607            Wacoal Women's Red Carpet Strapless Bra  $65.00   $65.00    
31608                 Wacoal Women's Underwire Sport Bra  $65.00   $54.50    
31609            Wacoal Women's Retro Chic Underwire Bra  $60.00   $60.00    
31610                  Wacoal Women's Halo Underwire Bra  $48.00   $48.00    
31611            Wacoal Women's Retro Chic Underwire Bra  $43.06   $43.06    

                                                 pdp_url    brand_name  \
0      https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1      https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   
2      https://www.amazon.com/-/dp/B000T3606Q?th=1&psc=1        Wacoal   
3      https://www.amazon.com/-/dp/B003Y6AX0Y?th=1&psc=1   Hanky-Panky   
4      https://www.amazon.com/-/dp/B01CEBGQA0?th=1&psc=1        Wacoal   
...                                                  ...           ...   
31607  https://www.amazon.com/-/dp/B01CEBGODE?th=1&psc=1        Wacoal   
31608  https://www.amazon.com/-/dp/B01GTNW0TA?th=1&psc=1        Wacoal   
31609  https://www.amazon.com/-/dp/B01N6KT7XE?th=1&psc=1        Wacoal   
31610  https://www.amazon.com/-/dp/B00SJ6UBTC?th=1&psc=1        Wacoal   
31611  https://www.amazon.com/-/dp/B01B4GBQ7O?th=1&psc=1        Wacoal   

      product_category   retailer  \
0                 Bras  Amazon US   
1              Panties  Amazon US   
2                 Bras  Amazon US   
3              Panties  Amazon US   
4                 Bras  Amazon US   
...                ...        ...   
31607             Bras  Amazon US   
31608             Bras  Amazon US   
31609             Bras  Amazon US   
31610             Bras  Amazon US   
31611             Bras  Amazon US   

                                             description  rating  \
0      An unlined demi cup bra featuring sheer, sexy ...     4.5   
1      Embrace lace bikini offers great fit and match...     4.4   
2      Seamless underwire minimizer bra gives great s...     4.3   
3      All-day comfort describes this figure-flatteri...     4.4   
4      Red Carpet full figure strapless fits great, s...     4.4   
...                                                  ...     ...   
31607  Red Carpet full figure strapless fits great, s...     4.4   
31608  Sport bra offers great control, support and co...     4.3   
31609  Beautiful low plunge chantilly lace bra with s...     4.4   
31610  Beautiful all over cross-dye soft lace cups an...     4.4   
31611  Beautiful low plunge chantilly lace bra with s...     4.4   

       review_count                                   style_attributes  \
0                47  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1                91  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   
2               298  [ Cups: 100% Polyester; Back: 71% Nylon, 29% S...   
3                46  [ Made in USA , All-day comfort describes this...   
4               747  [ 91% Nylon, 9% Spandex , Imported , hook and ...   
...             ...                                                ...   
31607           806  [ 91% Nylon, 9% Spandex , Imported , Hand Wash...   
31608          1846  [ 80% Nylon/ 20% Spandex/Elastane , Imported ,...   
31609           753  [ Lace: 100% Nylon; Back: 82% Nylon, 18% Spand...   
31610           379  [ 82% Nylon, 18% Spandex , Imported , Hook and...   
31611           753  [ Lace: 100% Nylon; Back: 82% Nylon, 18% Spand...   

                                             total_sizes  \
0      

In [65]:
amz_df.mrp.unique()

array(['$36.00 ', '$27.00 ', '$65.00 ', '$55.00 ', '$44.00 ', '$20.00 ',
       '$50.00 ', '$38.00 ', '$33.00 ', '$60.00 ', '$46.00 ', '$48.00 ',
       '$58.00 ', '$39.99 ', '$39.00 ', '$35.98 ', '$22.00 ', '$18.00 ',
       '$19.28 ', '$41.79 ', '$42.00 ', '$13.00 ', '$24.99 ', '$18.77 ',
       '$54.99 ', '$38.99 ', '$32.00 ', '$34.00 ', '$68.00 ', '$43.92 ',
       '$58.20 ', '$64.90 ', '$49.95 ', '$70.40 ', '$33.63 ', '$37.47 ',
       '$12.00 ', '$49.99 ', '$72.00 ', '$28.50 ', '$30.00 ', '$31.95 ',
       '$47.65 ', '$34.99 ', '$41.00 ', '$49.67 ', '$44.95 ', '$51.99 ',
       '$59.99 ', '$29.00 ', '$21.90 ', '$21.41 ', '$37.95 ', '$45.99 ',
       '$19.99 ', '$52.99 ', '$36.48 ', '$26.98 ', '$28.00 ', '$66.23 ',
       '$35.54 ', '$31.47 ', '$59.50 ', '$67.96 ', '$53.84 ', '$26.99 ',
       '$36.35 ', '$39.01 ', '$64.99 ', '$54.00 ', '$49.96 ', '$29.67 ',
       '$14.99 ', '$47.99 ', '$59.43 ', '$60.60 ', '$32.50 ', '$49.00 ',
       '$63.05 ', '$38.50 ', '$59.96 ', '$39.88 ', 

In [66]:
amz_df.price.unique()

array(['$32.40 ', '$27.00 ', '$65.00 ', ..., '$19.64 ', '$64.44 ',
       '$23.67 '], dtype=object)

In [67]:
amz_df.mrp = amz_df.mrp.str.strip('$')
amz_df.head()

product_name     mrp    price  \
0  Calvin Klein Women's Sheer Marquisette Demi Un...  36.00   $32.40    
1                   Wacoal Embrace Lace Bikini Panty  27.00   $27.00    
2     Wacoal Women's Slimline Seamless Minimizer Bra  65.00   $65.00    
3     Hanky Panky Womens Signature Lace Retro V-Kini  36.00   $36.00    
4            Wacoal Women's Red Carpet Strapless Bra  65.00   $65.00    

                                             pdp_url    brand_name  \
0  https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1  https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   
2  https://www.amazon.com/-/dp/B000T3606Q?th=1&psc=1        Wacoal   
3  https://www.amazon.com/-/dp/B003Y6AX0Y?th=1&psc=1   Hanky-Panky   
4  https://www.amazon.com/-/dp/B01CEBGQA0?th=1&psc=1        Wacoal   

  product_category   retailer  \
0             Bras  Amazon US   
1          Panties  Amazon US   
2             Bras  Amazon US   
3          Panties  Amazon US   
4             Bras  Amazon US   

                                         description  rating  review_count  \
0  An unlined demi cup bra featuring sheer, sexy ...     4.5            47   
1  Embrace lace bikini offers great fit and match...     4.4            91   
2  Seamless underwire minimizer bra gives great s...     4.3           298   
3  All-day comfort describes this figure-flatteri...     4.4            46   
4  Red Carpet full figure strapless fits great, s...     4.4           747   

                                    style_attributes  \
0  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   
2  [ Cups: 100% Polyester; Back: 71% Nylon, 29% S...   
3  [ Made in USA , All-day comfort describes this...   
4  [ 91% Nylon, 9% Spandex , Imported , hook and ...   

                                         total_sizes  \
0  30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...   
1                   Small , Medium , Large , X-Large   
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...   
3                   Small , Medium , Large , X-Large   
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...   

                                      available_size  color  
0  30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...   Bare  
1                           Small , Medium , X-Large  Large  
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...  Black  
3                           Small , Medium , X-Large  Large  
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...  Pecan

In [68]:
amz_df.mrp = amz_df.mrp.str.strip(' ')
amz_df.head()

product_name    mrp    price  \
0  Calvin Klein Women's Sheer Marquisette Demi Un...  36.00  $32.40    
1                   Wacoal Embrace Lace Bikini Panty  27.00  $27.00    
2     Wacoal Women's Slimline Seamless Minimizer Bra  65.00  $65.00    
3     Hanky Panky Womens Signature Lace Retro V-Kini  36.00  $36.00    
4            Wacoal Women's Red Carpet Strapless Bra  65.00  $65.00    

                                             pdp_url    brand_name  \
0  https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1  https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   
2  https://www.amazon.com/-/dp/B000T3606Q?th=1&psc=1        Wacoal   
3  https://www.amazon.com/-/dp/B003Y6AX0Y?th=1&psc=1   Hanky-Panky   
4  https://www.amazon.com/-/dp/B01CEBGQA0?th=1&psc=1        Wacoal   

  product_category   retailer  \
0             Bras  Amazon US   
1          Panties  Amazon US   
2             Bras  Amazon US   
3          Panties  Amazon US   
4             Bras  Amazon US   

                                         description  rating  review_count  \
0  An unlined demi cup bra featuring sheer, sexy ...     4.5            47   
1  Embrace lace bikini offers great fit and match...     4.4            91   
2  Seamless underwire minimizer bra gives great s...     4.3           298   
3  All-day comfort describes this figure-flatteri...     4.4            46   
4  Red Carpet full figure strapless fits great, s...     4.4           747   

                                    style_attributes  \
0  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   
2  [ Cups: 100% Polyester; Back: 71% Nylon, 29% S...   
3  [ Made in USA , All-day comfort describes this...   
4  [ 91% Nylon, 9% Spandex , Imported , hook and ...   

                                         total_sizes  \
0  30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...   
1                   Small , Medium , Large , X-Large   
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...   
3                   Small , Medium , Large , X-Large   
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...   

                                      available_size  color  
0  30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...   Bare  
1                           Small , Medium , X-Large  Large  
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...  Black  
3                           Small , Medium , X-Large  Large  
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...  Pecan

In [69]:
amz_df.mrp = amz_df.mrp.astype(float)

amz_df.head()

product_name   mrp    price  \
0  Calvin Klein Women's Sheer Marquisette Demi Un...  36.0  $32.40    
1                   Wacoal Embrace Lace Bikini Panty  27.0  $27.00    
2     Wacoal Women's Slimline Seamless Minimizer Bra  65.0  $65.00    
3     Hanky Panky Womens Signature Lace Retro V-Kini  36.0  $36.00    
4            Wacoal Women's Red Carpet Strapless Bra  65.0  $65.00    

                                             pdp_url    brand_name  \
0  https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1  https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   
2  https://www.amazon.com/-/dp/B000T3606Q?th=1&psc=1        Wacoal   
3  https://www.amazon.com/-/dp/B003Y6AX0Y?th=1&psc=1   Hanky-Panky   
4  https://www.amazon.com/-/dp/B01CEBGQA0?th=1&psc=1        Wacoal   

  product_category   retailer  \
0             Bras  Amazon US   
1          Panties  Amazon US   
2             Bras  Amazon US   
3          Panties  Amazon US   
4             Bras  Amazon US   

                                         description  rating  review_count  \
0  An unlined demi cup bra featuring sheer, sexy ...     4.5            47   
1  Embrace lace bikini offers great fit and match...     4.4            91   
2  Seamless underwire minimizer bra gives great s...     4.3           298   
3  All-day comfort describes this figure-flatteri...     4.4            46   
4  Red Carpet full figure strapless fits great, s...     4.4           747   

                                    style_attributes  \
0  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   
2  [ Cups: 100% Polyester; Back: 71% Nylon, 29% S...   
3  [ Made in USA , All-day comfort describes this...   
4  [ 91% Nylon, 9% Spandex , Imported , hook and ...   

                                         total_sizes  \
0  30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...   
1                   Small , Medium , Large , X-Large   
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...   
3                   Small , Medium , Large , X-Large   
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...   

                                      available_size  color  
0  30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...   Bare  
1                           Small , Medium , X-Large  Large  
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...  Black  
3                           Small , Medium , X-Large  Large  
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...  Pecan

In [70]:
amz_df.price = amz_df.price.str.strip('$')
amz_df.head()

product_name   mrp   price  \
0  Calvin Klein Women's Sheer Marquisette Demi Un...  36.0  32.40    
1                   Wacoal Embrace Lace Bikini Panty  27.0  27.00    
2     Wacoal Women's Slimline Seamless Minimizer Bra  65.0  65.00    
3     Hanky Panky Womens Signature Lace Retro V-Kini  36.0  36.00    
4            Wacoal Women's Red Carpet Strapless Bra  65.0  65.00    

                                             pdp_url    brand_name  \
0  https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1  https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   
2  https://www.amazon.com/-/dp/B000T3606Q?th=1&psc=1        Wacoal   
3  https://www.amazon.com/-/dp/B003Y6AX0Y?th=1&psc=1   Hanky-Panky   
4  https://www.amazon.com/-/dp/B01CEBGQA0?th=1&psc=1        Wacoal   

  product_category   retailer  \
0             Bras  Amazon US   
1          Panties  Amazon US   
2             Bras  Amazon US   
3          Panties  Amazon US   
4             Bras  Amazon US   

                                         description  rating  review_count  \
0  An unlined demi cup bra featuring sheer, sexy ...     4.5            47   
1  Embrace lace bikini offers great fit and match...     4.4            91   
2  Seamless underwire minimizer bra gives great s...     4.3           298   
3  All-day comfort describes this figure-flatteri...     4.4            46   
4  Red Carpet full figure strapless fits great, s...     4.4           747   

                                    style_attributes  \
0  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   
2  [ Cups: 100% Polyester; Back: 71% Nylon, 29% S...   
3  [ Made in USA , All-day comfort describes this...   
4  [ 91% Nylon, 9% Spandex , Imported , hook and ...   

                                         total_sizes  \
0  30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...   
1                   Small , Medium , Large , X-Large   
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...   
3                   Small , Medium , Large , X-Large   
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...   

                                      available_size  color  
0  30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...   Bare  
1                           Small , Medium , X-Large  Large  
2  32DD , 32DDD , 34C , 34D , 34DD , 34DDD , 36C ...  Black  
3                           Small , Medium , X-Large  Large  
4  30D , 30DD , 30DDD , 30G , 32C , 32D , 32DD , ...  Pecan

In [71]:
amz_df.price = amz_df.price.str.strip(' ').astype(float)

In [72]:
amz_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count          int64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [73]:
amz_df.isnull().sum()

product_name        0
mrp                 0
price               0
pdp_url             0
brand_name          0
product_category    0
retailer            0
description         0
rating              0
review_count        0
style_attributes    0
total_sizes         0
available_size      0
color               0
dtype: int64

In [74]:
amz_df['parent_category'] = amz_df['product_category']

In [75]:
amz_df.parent_category.unique()

array(['Bras', 'Panties'], dtype=object)

No nulls, so I don't need to impute any data for ratings the way I did for AE.

### b.tempt'd by Wacoal

In [76]:
btd_df = pd.read_csv('btemptd_com.csv')
btd_df.head()

product_name      mrp    price  \
0  b.tempt'd Ciao Bella Bralette  $30.00   $30.00    
1  b.tempt'd Ciao Bella Bralette  $30.00   $30.00    
2  b.tempt'd Ciao Bella Bralette  $30.00   $30.00    
3  b.tempt'd Ciao Bella Bralette  $30.00   $21.00    
4  b.tempt'd Ciao Bella Bralette  $30.00   $21.00    

                                             pdp_url brand_name  \
0  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   
1  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   
2  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   
3  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   
4  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   

  product_category    retailer  \
0      COLLECTIONS  Btemptd US   
1      COLLECTIONS  Btemptd US   
2      COLLECTIONS  Btemptd US   
3      COLLECTIONS  Btemptd US   
4      COLLECTIONS  Btemptd US   

                                         description  rating  review_count  \
0  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   
1  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   
2  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   
3  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   
4  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   

                                    style_attributes  total_sizes  \
0  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   
1  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   
2  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   
3  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   
4  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   

  available_size          color  
0    l,m,s,xl,xs   Bridal White  
1    l,m,s,xl,xs          Night  
2    l,m,s,xl,xs     Wild Aster  
3    l,m,s,xl,xs  Camellia Rose  
4    l,m,s,xl,xs     Cappuccino

In [77]:
btd_df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [78]:
btd_df.mrp.unique()

array(['$30.00 ', '$40.00 ', '$44.00 ', '$39.00 ', '$13.00 ', '$34.00 ',
       '$18.00 ', '$42.00 ', '$45.00 ', '$19.00 ', '$22.00 ', '$32.00 ',
       '$26.00 ', '$24.00 ', '$20.00 ', '$21.00 ', '$46.00 ', '$38.00 ',
       '$36.00 ', '$35.00 ', '$33.00 ', '$25.00 '], dtype=object)

In [79]:
btd_df.price.unique()

array(['$30.00 ', '$21.00 ', '$18.00 ', '$40.00 ', '$44.00 ', '$30.80 ',
       '$26.40 ', '$23.40 ', '$13.00 ', '$9.10 ', '$7.80 ', '$23.80 ',
       '$34.00 ', '$24.00 ', '$12.60 ', '$10.80 ', '$42.00 ', '$27.00 ',
       '$45.00 ', '$11.40 ', '$25.20 ', '$22.00 ', '$32.00 ', '$22.40 ',
       '$19.20 ', '$18.20 ', '$19.00 ', '$13.30 ', '$29.40 ', '$14.40 ',
       '$20.00 ', '$15.40 ', '$13.20 ', '$32.20 ', '$38.00 ', '$26.60 ',
       '$22.80 ', '$19.80 ', '$17.50 ', '$15.00 ', '$28.00 ', '$35.00 ',
       '$24.50 ', '$12.00 ', '$14.00 ', '$23.10 ', '$31.50 ', '$16.80 ',
       '$36.00 ', '$26.00 ', '$46.00 '], dtype=object)

In [80]:
btd_df.mrp = btd_df.mrp.str.strip('$').str.strip(' ').astype(float)

In [81]:
btd_df.price = btd_df.price.str.strip('$').str.strip(' ').astype(float)

In [82]:
btd_df.head(2)

product_name   mrp  price  \
0  b.tempt'd Ciao Bella Bralette  30.0   30.0   
1  b.tempt'd Ciao Bella Bralette  30.0   30.0   

                                             pdp_url brand_name  \
0  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   
1  http://btemptd.wacoal-america.com/b-tempt-d-ci...     WACOAL   

  product_category    retailer  \
0      COLLECTIONS  Btemptd US   
1      COLLECTIONS  Btemptd US   

                                         description  rating  review_count  \
0  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   
1  Say “buongiorno!” to this ladylike piece that ...     NaN           NaN   

                                    style_attributes  total_sizes  \
0  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   
1  [Wire free bralette • Cut and sew corded lace ...  XS,S,M,L,XL   

  available_size         color  
0    l,m,s,xl,xs  Bridal White  
1    l,m,s,xl,xs         Night

In [83]:
btd_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

Parent category will need to be added based on what is contained in either product_name or style_attributes.

In [84]:
btd_df.product_name.unique()

array(["b.tempt'd Ciao Bella Bralette", 'b.charming T-Shirt Bra',
       'b.splendid Underwire T-shirt Bra', 'b.sultry Underwire Bra',
       'b.sultry Thong', 'b.provocative Underwire T-shirt Bra',
       'b.sultry Bikini', 'b.sleek Bikini', 'b.inspired Bralette',
       'b.provocative Underwire Bra', 'b.cherished Thong',
       "b.tempt'd Lace Kiss Bralette", 'b.gorgeous Bikini',
       "b.tempt'd Lace Kiss Bikini", 'b.adorable Chemise',
       'b.sultry Chemise', "b.tempt'd Most Desired Thong",
       'b.splendid Hipster', 'b.sleek Thong', 'b.provocative Bikini',
       "b.tempt'd Ciao Bella Bikini", "b.wow'd by b.tempt'd Push Up Bra",
       'b.bare thong', "b.tempt'd Most Desired Hipster",
       'b.sumptuous Underwire Balconette Bra', 'Lace Kiss Bandeau',
       'b.provocative Front Close Wire Free Bralette',
       'Ciao Bella Wire Free Bralette', "b.tempt'd Lace Kiss Hipster",
       'b.enticing Boyshort',
       "b.tempt'd Faithfully Yours Strapless Underwire Bra",
       'b.s

In [85]:
btd_df.style_attributes.unique()

array(['[Wire free bralette • Cut and sew corded lace cups with contrast lining• Dramatic scallop detail at neckline • Fishnet mesh lined band• Hook and eye back closure • Double roleau straps with back adjustment• Matching panties 976144, 978144, 945144 (sold separately), Body: 86% Nylon/14% Spandex ,Hand wash warm,Wash colors separately,Use non-chlorine bleach only when needed,Hang to dry,Do not iron,Do not dry clean]',
       '[Underwire t-shirt bra,Cups with stretch foam pads covered in novelty pique fabric ,Top cup covered with eyelet inspired lace,Pretty detailed edge at top of cups with bow accents at strap,Soft pique fabric provides added band comfort,Low center front with lace bow detail,Fully adjustable decorative stretch straps ,Matching panties 945232 (sold separately), Body: 41% Nylon/ 39% Polyester/ 20% Spandex; Top Cup: 87% Nylon/ 13% Spandex; Cup Lining: 100% Polyester ,Hand wash warm,Wash colors separately,Use non-chlorine bleach only when needed,Hang to dry,Do not iro

In [86]:
btd_df.product_category.unique()

array(['COLLECTIONS', 'BRAS AND BRALETTES', 'PANTIES'], dtype=object)

In [87]:
btd_df[btd_df['product_category'] == 'COLLECTIONS'].shape

(1552, 14)

In [88]:
btd_df.shape

(3518, 14)

In [89]:
(1552/3518)*100

44.11597498578738

Choosing to drop the COLLECTIONS items; there is no way to extrapolate the parent category that is within the scope of this project. Will table for future work.

In [90]:
btd_df.drop(btd_df[btd_df.product_category == 'COLLECTIONS'].index, inplace=True)

In [91]:
btd_df[btd_df['product_category'] == 'COLLECTIONS']

Empty DataFrame
Columns: [product_name, mrp, price, pdp_url, brand_name, product_category, retailer, description, rating, review_count, style_attributes, total_sizes, available_size, color]
Index: []

In [92]:
btd_df.product_category.unique()

array(['BRAS AND BRALETTES', 'PANTIES'], dtype=object)

In [93]:
btd_cat_dict = {'BRAS AND BRALETTES':'Bras', 'PANTIES':'Panties'}

btd_df['parent_category'] = btd_df.product_category.map(btd_cat_dict)

In [94]:
btd_df.head()

product_name   mrp  price  \
11  b.splendid Underwire T-shirt Bra  44.0   44.0   
12  b.splendid Underwire T-shirt Bra  44.0   44.0   
13  b.splendid Underwire T-shirt Bra  44.0   44.0   
14  b.splendid Underwire T-shirt Bra  44.0   44.0   
15  b.splendid Underwire T-shirt Bra  44.0   30.8   

                                              pdp_url brand_name  \
11  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   
12  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   
13  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   
14  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   
15  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   

      product_category    retailer  \
11  BRAS AND BRALETTES  Btemptd US   
12  BRAS AND BRALETTES  Btemptd US   
13  BRAS AND BRALETTES  Btemptd US   
14  BRAS AND BRALETTES  Btemptd US   
15  BRAS AND BRALETTES  Btemptd US   

                                          description  rating  review_count  \
11  With underwire concealed between layers of foa...     NaN           NaN   
12  With underwire concealed between layers of foa...     NaN           NaN   
13  With underwire concealed between layers of foa...     NaN           NaN   
14  With underwire concealed between layers of foa...     NaN           NaN   
15  With underwire concealed between layers of foa...     NaN           NaN   

                                     style_attributes  \
11  [Underwire t-shirt bra,Stretch foam cups,Soft ...   
12  [Underwire t-shirt bra,Stretch foam cups,Soft ...   
13  [Underwire t-shirt bra,Stretch foam cups,Soft ...   
14  [Underwire t-shirt bra,Stretch foam cups,Soft ...   
15  [Underwire t-shirt bra,Stretch foam cups,Soft ...   

                                          total_sizes  \
11  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   
12  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   
13  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   
14  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   
15  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   

                                       available_size                   color  \
11  30c,30d,30dd,32b,32c,32d,32dd,32ddd,34a,34b,34...  Cherry Blossom Heather   
12  36d,30c,30d,30dd,30ddd,32a,32b,32c,32d,32dd,32...           Pansy Heather   
13  30c,30d,30dd,30ddd,32a,32b,32d,32dd,32ddd,34a,...      Au Natural/Heather   
14  30c,30d,30dd,30ddd,32a,32b,32c,32d,32dd,32ddd,...       Dark Grey/Heather   
15  30c,30d,30dd,30ddd,32a,32b,32c,32d,32dd,32ddd,...     Pink Yarrow Heather   

   parent_category  
11            Bras  
12            Bras  
13            Bras  
14            Bras  
15            Bras

In [95]:
btd_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              1966
review_count        1966
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

In [96]:
btd_df.groupby(['parent_category']).mean()

mrp      price  rating  review_count
parent_category                                            
Bras             35.084337  29.081124     NaN           NaN
Panties          14.439705  11.517637     NaN           NaN

In [97]:
btd_df.shape

(1966, 15)

Nothing has been rated or reviewed. As much as I would like to include more data in order to get the best possible model, I believe rating may play a large part in my modeling. Will table for the time being.

In [98]:
btd_df.review_count.fillna(0, inplace=True)

In [99]:
btd_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              1966
review_count           0
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

### Calvin Klein

In [100]:
ck_df = pd.read_csv('calvinklein_com.csv')
ck_df.head()

product_name      mrp    price  \
0  logo cotton stretch thong  $13.00   $13.00    
1  logo cotton stretch thong  $13.00   $13.00    
2  logo cotton stretch thong  $13.00   $13.00    
3  logo cotton stretch thong  $13.00   $13.00    
4           essentials thong  $13.00   $13.00    

                                             pdp_url    brand_name  \
0  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
1  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
2  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
3  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   

            product_category         retailer  \
0  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
1  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
2  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
3  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
4                    Panties  Calvin Klein US   

                                         description  rating  review_count  \
0  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
1  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
2  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
3  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
4  the essentials thong features a semi sheer pat...     NaN           NaN   

                                    style_attributes total_sizes  \
0  ["cotton stretch thong panty","metallic elasti...       s,m,l   
1  ["cotton stretch thong panty","metallic elasti...       s,m,l   
2  ["cotton stretch thong panty","metallic elasti...       s,m,l   
3  ["cotton stretch thong panty","metallic elasti...       s,m,l   
4  ["semi sheer thong panty","thin elastic logo w...       s,m,l   

  available_size                             color  
0          s,m,l                             BLACK  
1          s,m,l                      ASHFORD GREY  
2          s,m,l                             WHITE  
3          s,m,l                              NAVY  
4          s,m,l  EPHEMERAL WITH IVORY LACE & LOGO

In [101]:
ck_df.mrp.unique()

array(['$13.00 ', '$18.00 ', '$24.00 ', '$20.00 ', '$22.00 ', '$42.00 ',
       '$28.00 ', '$39.00 ', '$38.00 ', '$36.00 ', '$40.00 ', '$44.00 ',
       '$48.00 ', '$50.00 ', '$46.00 ', '$59.00 ', '$26.00 ', '$32.00 ',
       '$12.00 ', '$34.00 ', '$49.00 ', '$62.00 ', '$58.00 ', '$72.00 '],
      dtype=object)

In [102]:
ck_df.price.unique()

array(['$13.00 ', '$18.00 ', '$24.00 ', '$20.00 ', '$22.00 ', '$42.00 ',
       '$28.00 ', '$24.99 ', '$19.99 ', '$6.99 ', '$38.00 ', '$36.00 ',
       '$40.00 ', '$44.00 ', '$34.99 ', '$29.99 ', '$14.99 ', '$46.00 ',
       '$9.99 ', '$39.00 ', '$26.00 ', '$50.00 ', '$12.99 ', '$32.00 ',
       '$16.99 ', '$12.00 ', '$4.99 ', '$19.99 - $24.99', '$49.00 ',
       '$48.00 ', '$39.99 ', '$58.00 ', '$39.50 ', '$72.00 ', '$34.00 ',
       '$59.00 ', '$34.50 '], dtype=object)

In [103]:
ck_df.mrp = ck_df.mrp.str.strip('$').str.strip(' ').astype(float)
ck_df.price = ck_df.price.str.strip('$').str.strip(' ').astype(float)

ValueError: could not convert string to float: '19.99 - $24.99'

In [104]:
ck_df.price.unique()

array(['$13.00 ', '$18.00 ', '$24.00 ', '$20.00 ', '$22.00 ', '$42.00 ',
       '$28.00 ', '$24.99 ', '$19.99 ', '$6.99 ', '$38.00 ', '$36.00 ',
       '$40.00 ', '$44.00 ', '$34.99 ', '$29.99 ', '$14.99 ', '$46.00 ',
       '$9.99 ', '$39.00 ', '$26.00 ', '$50.00 ', '$12.99 ', '$32.00 ',
       '$16.99 ', '$12.00 ', '$4.99 ', '$19.99 - $24.99', '$49.00 ',
       '$48.00 ', '$39.99 ', '$58.00 ', '$39.50 ', '$72.00 ', '$34.00 ',
       '$59.00 ', '$34.50 '], dtype=object)

In [105]:
ck_df[ck_df['price'] == '$19.99 - $24.99']

product_name   mrp            price  \
420   essentials push-up bra  39.0  $19.99 - $24.99   
421   essentials push-up bra  39.0  $19.99 - $24.99   
422   essentials push-up bra  39.0  $19.99 - $24.99   
423   essentials push-up bra  39.0  $19.99 - $24.99   
424   essentials push-up bra  39.0  $19.99 - $24.99   
425   essentials push-up bra  39.0  $19.99 - $24.99   
4244  essentials push-up bra  39.0  $19.99 - $24.99   
4245  essentials push-up bra  39.0  $19.99 - $24.99   
4246  essentials push-up bra  39.0  $19.99 - $24.99   
4247  essentials push-up bra  39.0  $19.99 - $24.99   
4248  essentials push-up bra  39.0  $19.99 - $24.99   
4249  essentials push-up bra  39.0  $19.99 - $24.99   

                                                pdp_url    brand_name  \
420   http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
421   http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
422   http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
423   http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
424   http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
425   http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4244  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4245  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4246  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4247  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4248  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4249  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   

     product_category         retailer  \
420              Bras  Calvin Klein US   
421              Bras  Calvin Klein US   
422              Bras  Calvin Klein US   
423              Bras  Calvin Klein US   
424              Bras  Calvin Klein US   
425              Bras  Calvin Klein US   
4244             Bras  Calvin Klein US   
4245             Bras  Calvin Klein US   
4246             Bras  Calvin Klein US   
4247             Bras  Calvin Klein US   
4248             Bras  Calvin Klein US   
4249             Bras  Calvin Klein US   

                                            description  rating  review_count  \
420   part of wardrobe essentials, push-up padding a...     NaN           NaN   
421   part of wardrobe essentials, push-up padding a...     NaN           NaN   
422   part of wardrobe essentials, push-up padding a...     NaN           NaN   
423   part of wardrobe essentials, push-up padding a...     NaN           NaN   
424   part of wardrobe essentials, push-up padding a...     NaN           NaN   
425   part of wardrobe essentials, push-up padding a...     NaN           NaN   
4244  part of wardrobe essentials, push-up padding a...     NaN           NaN   
4245  part of wardrobe essentials, push-up padding a...     NaN           NaN   
4246  part of wardrobe essentials, push-up padding a...     NaN           NaN   
4247  part of wardrobe essentials, push-up padding a...     NaN           NaN   
4248  part of wardrobe essentials, push-up padding a...     NaN           NaN   
4249  part of wardrobe essentials, push-up padding a...     NaN           NaN   

                                       style_attributes  \
420   ["push-up bra","moderate coverage","padded cup...   
421   ["push-up bra","moderate coverage","padded cup...   
422   ["push-up bra","moderate coverage","padded cup...   
423   ["push-up bra","moderate coverage","padded cup...   
424   ["push-up bra","moderate coverage","padded cup...   
425   ["push-up bra","moderate coverage","padded cup...   
4244  ["push-up bra","moderate coverage","padded cup...   
4245  ["push-up bra","moderate coverage","padded cup...   
4246  ["push-up bra","moderate coverage","padded cup...   
4247  ["push-up bra","moderate coverage","padded cup...   
4248  ["push-up bra","moderate coverage","padded cup...   
4249  ["push-up bra","moderate coverage",

Drawing on my retail knowledge, I'm going to assume that the essentials push-up bra has multiple colors living on the same product page and some were marked down to 19.99 and some were 24.99 at the time the data was pulled. I'm going to choose the max of this range, given that each color was probably at this markdown price before being lowered.

In [106]:
ck_df.price.replace(to_replace='$19.99 - $24.99', value='$24.99', inplace=True)

In [107]:
ck_df.price.unique()

array(['$13.00 ', '$18.00 ', '$24.00 ', '$20.00 ', '$22.00 ', '$42.00 ',
       '$28.00 ', '$24.99 ', '$19.99 ', '$6.99 ', '$38.00 ', '$36.00 ',
       '$40.00 ', '$44.00 ', '$34.99 ', '$29.99 ', '$14.99 ', '$46.00 ',
       '$9.99 ', '$39.00 ', '$26.00 ', '$50.00 ', '$12.99 ', '$32.00 ',
       '$16.99 ', '$12.00 ', '$4.99 ', '$24.99', '$49.00 ', '$48.00 ',
       '$39.99 ', '$58.00 ', '$39.50 ', '$72.00 ', '$34.00 ', '$59.00 ',
       '$34.50 '], dtype=object)

In [108]:
ck_df.price = ck_df.price.str.strip('$').str.strip(' ').astype(float)

In [109]:
ck_df.head()

product_name   mrp  price  \
0  logo cotton stretch thong  13.0   13.0   
1  logo cotton stretch thong  13.0   13.0   
2  logo cotton stretch thong  13.0   13.0   
3  logo cotton stretch thong  13.0   13.0   
4           essentials thong  13.0   13.0   

                                             pdp_url    brand_name  \
0  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
1  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
2  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
3  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   

            product_category         retailer  \
0  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
1  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
2  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
3  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
4                    Panties  Calvin Klein US   

                                         description  rating  review_count  \
0  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
1  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
2  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
3  soft cotton stretch fabric and a metallic logo...     NaN           NaN   
4  the essentials thong features a semi sheer pat...     NaN           NaN   

                                    style_attributes total_sizes  \
0  ["cotton stretch thong panty","metallic elasti...       s,m,l   
1  ["cotton stretch thong panty","metallic elasti...       s,m,l   
2  ["cotton stretch thong panty","metallic elasti...       s,m,l   
3  ["cotton stretch thong panty","metallic elasti...       s,m,l   
4  ["semi sheer thong panty","thin elastic logo w...       s,m,l   

  available_size                             color  
0          s,m,l                             BLACK  
1          s,m,l                      ASHFORD GREY  
2          s,m,l                             WHITE  
3          s,m,l                              NAVY  
4          s,m,l  EPHEMERAL WITH IVORY LACE & LOGO

In [110]:
ck_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [111]:
ck_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              4747
review_count        4747
style_attributes       0
total_sizes            0
available_size         0
color                  0
dtype: int64

In [112]:
ck_df.shape

(4747, 14)

In [113]:
ck_df.review_count.fillna(0, inplace=True)
ck_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              4747
review_count           0
style_attributes       0
total_sizes            0
available_size         0
color                  0
dtype: int64

At this point, I don't want to lose two datasets for having no rating. I will combine b'temptd and Calvin Klein with the rest and manage my nulls from there.

In [114]:
#Create parent_category
ck_df.product_category.unique()

array(['3 FOR 33 PANTY ESSENTIALS', 'Panties', 'Socks', 'Bras',
       'Sleepwear', 'Bralettes', 'Panty Sets'], dtype=object)

In [115]:
ck_cat_dict = {
    '3 FOR 33 PANTY ESSENTIALS':'Panties',
    'Panties':'Panties',
    'Bras':'Bras',
    'Bralettes':'Bras',
    'Panty Sets':'Panties'
}

In [116]:
ck_df['parent_category'] = ck_df.product_category.map(ck_cat_dict)

In [117]:
ck_df.head()

product_name   mrp  price  \
0  logo cotton stretch thong  13.0   13.0   
1  logo cotton stretch thong  13.0   13.0   
2  logo cotton stretch thong  13.0   13.0   
3  logo cotton stretch thong  13.0   13.0   
4           essentials thong  13.0   13.0   

                                             pdp_url    brand_name  \
0  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
1  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
2  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
3  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
4  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   

            product_category         retailer  \
0  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
1  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
2  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
3  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
4                    Panties  Calvin Klein US   

                                         description  rating  review_count  \
0  soft cotton stretch fabric and a metallic logo...     NaN           0.0   
1  soft cotton stretch fabric and a metallic logo...     NaN           0.0   
2  soft cotton stretch fabric and a metallic logo...     NaN           0.0   
3  soft cotton stretch fabric and a metallic logo...     NaN           0.0   
4  the essentials thong features a semi sheer pat...     NaN           0.0   

                                    style_attributes total_sizes  \
0  ["cotton stretch thong panty","metallic elasti...       s,m,l   
1  ["cotton stretch thong panty","metallic elasti...       s,m,l   
2  ["cotton stretch thong panty","metallic elasti...       s,m,l   
3  ["cotton stretch thong panty","metallic elasti...       s,m,l   
4  ["semi sheer thong panty","thin elastic logo w...       s,m,l   

  available_size                             color parent_category  
0          s,m,l                             BLACK         Panties  
1          s,m,l                      ASHFORD GREY         Panties  
2          s,m,l                             WHITE         Panties  
3          s,m,l                              NAVY         Panties  
4          s,m,l  EPHEMERAL WITH IVORY LACE & LOGO         Panties

I have chosen to table items that cannot be categorized broadly under Bras and Panties.

In [118]:
#Automating dropping multiple product categories.

drop_prod_list = ['Socks', 'Sleepwear']

for i in drop_prod_list:
    ck_df.drop(ck_df[ck_df.product_category == i].index, inplace=True)

In [119]:
ck_df.product_category.unique()

array(['3 FOR 33 PANTY ESSENTIALS', 'Panties', 'Bras', 'Bralettes',
       'Panty Sets'], dtype=object)

### Hanky Panky

In [120]:
hankypanky_df = pd.read_csv('hankypanky_com.csv')

hankypanky_df.head()

product_name   mrp price  \
0  Silky 20” A-line Half Slip with Lace  $68   $68    
1  Silky 20” A-line Half Slip with Lace  $68   $68    
2            Peek-a-Boo Side Tie Bikini  $30   $30    
3            Peek-a-Boo Side Tie Bikini  $30   $30    
4        All Tied Up Tie Front Bralette  $59   $59    

                                             pdp_url  brand_name  \
0  http://www.hankypanky.com/collections/silky-20...  HankyPanky   
1  http://www.hankypanky.com/collections/silky-20...  HankyPanky   
2  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
3  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
4  http://www.hankypanky.com/collections/all-tied...  HankyPanky   

  product_category       retailer  \
0      Collections  Hankypanky US   
1      Collections  Hankypanky US   
2          Panties  Hankypanky US   
3          Panties  Hankypanky US   
4      Collections  Hankypanky US   

                                         description  rating  review_count  \
0  Hanky Panky Silky is the ideal fabric for unde...     NaN           NaN   
1  Hanky Panky Silky is the ideal fabric for unde...     NaN           NaN   
2  Don't go on your honeymoon without this pretty...     NaN           NaN   
3  Don't go on your honeymoon without this pretty...     NaN           NaN   
4                   All Tied Up in ribbons and lace.     NaN           NaN   

                                    style_attributes  \
0  ["Just above-the-knee-length half-slip with el...   
1  ["Just above-the-knee-length half-slip with el...   
2  ["Bikini-style panty in sheer lace ", " Featur...   
3  ["Bikini-style panty in sheer lace ", " Featur...   
4  ["Bralette in scalloped cross-dyed lace", " Fl...   

                       total_sizes                   available_size  \
0  ["Select", "S", "M", "L", "XL"]  ["Select", "S", "M", "L", "XL"]   
1  ["Select", "S", "M", "L", "XL"]  ["Select", "S", "M", "L", "XL"]   
2        ["Select", "S", "M", "L"]        ["Select", "S", "M", "L"]   
3        ["Select", "S", "M", "L"]        ["Select", "S", "M", "L"]   
4       ["Select", "XS", "S", "M"]       ["Select", "XS", "S", "M"]   

         color  
0        Black  
1        Mocha  
2        Black  
3  Light Ivory  
4   Black Plum

In [121]:
hankypanky_df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [122]:
hankypanky_df.mrp.unique()

array(['$68 ', '$30 ', '$59 ', '$615 ', '$64 ', '$86 ', '$60 ', '$23 ',
       '$82 ', '$90 ', '$34 ', '$96 ', '$39 ', '$41 ', '$49 ', '$58 ',
       '$32 ', '$102 ', '$92 ', '$50 ', '$69 ', '$140 ', '$53 ', '$24 ',
       '$56 ', '$160 ', '$25 ', '$126 ', '$20 ', '$48 ', '$62 ', '$22 ',
       '$54 ', '$36 ', '$15 ', '$35 ', '$28 ', '$14 ', '$47 ', '$110 ',
       '$78 ', '$52 ', '$67 ', '$72 ', '$79 ', '$70 ', '$44 ', '$29 ',
       '$42 ', '$128 ', '$83 ', '$108 ', '$40 ', '$38 ', '$75 ', '$158 ',
       '$186 ', '$106 ', '$94 ', '$135 ', '$57 ', '$89 ', '$85 ', '$27 ',
       '$32.50 ', '$46 ', '$18 ', '$10 ', '$80 ', '$84 ', '$19 ', '$112 ',
       '$98 ', '$63 ', '$74 ', '$66 ', '$26 ', '$55 ', '$21 ', '$118 ',
       '$116 ', '$11 ', '$100 ', '$165 ', '$43 ', '$125 ', '$12 ',
       '$295 ', '$65 ', '$45 ', '$33 ', '$71 ', '$37 ', '$95 ', '$114 ',
       '$31 ', '$105 ', '$88 ', '$99 ', '$300 ', '$73 ', '$150 '],
      dtype=object)

In [123]:
hankypanky_df.price.unique()

array(['$68 ', '$30 ', '$59 ', '$615 ', '$64 ', '$86 ', '$60 ', '$23 ',
       '$82 ', '$90 ', '$34 ', '$96 ', '$39 ', '$41 ', '$49 ', '$58 ',
       '$32 ', '$102 ', '$92 ', '$50 ', '$69 ', '$140 ', '$53 ', '$24 ',
       '$56 ', '$160 ', '$25 ', '$126 ', '$20 ', '$48 ', '$62 ', '$22 ',
       '$54 ', '$36 ', '$15 ', '$35 ', '$28 ', '$14 ', '$47 ', '$110 ',
       '$78 ', '$52 ', '$67 ', '$72 ', '$79 ', '$70 ', '$44 ', '$29 ',
       '$42 ', '$128 ', '$83 ', '$31.99 ', '$108 ', '$40 ', '$38 ',
       '$75 ', '$158 ', '$186 ', '$106 ', '$94 ', '$135 ', '$57 ',
       '$58.99 ', '$85 ', '$27 ', '$32.50 ', '$46 ', '$18 ', '$10 ',
       '$80 ', '$84 ', '$19 ', '$112 ', '$98 ', '$63 ', '$74 ', '$66 ',
       '$26 ', '$55 ', '$21 ', '$118 ', '$116 ', '$89 ', '$11 ', '$100 ',
       '$165 ', '$43 ', '$125 ', '$12 ', '$295 ', '$65 ', '$26.99 ',
       '$45 ', '$33 ', '$71 ', '$37 ', '$95 ', '$114 ', '$31 ', '$105 ',
       '$88 ', '$99 ', '$25.99 ', '$300 ', '$16.99 ', '$73 ', '$150 ',
     

In [124]:
hankypanky_df.mrp = hankypanky_df.mrp.str.strip('$').str.strip(' ').astype(float)

hankypanky_df.price = hankypanky_df.price.str.strip('$').str.strip(' ').astype(float)

In [125]:
hankypanky_df.mrp.unique()

array([ 68. ,  30. ,  59. , 615. ,  64. ,  86. ,  60. ,  23. ,  82. ,
        90. ,  34. ,  96. ,  39. ,  41. ,  49. ,  58. ,  32. , 102. ,
        92. ,  50. ,  69. , 140. ,  53. ,  24. ,  56. , 160. ,  25. ,
       126. ,  20. ,  48. ,  62. ,  22. ,  54. ,  36. ,  15. ,  35. ,
        28. ,  14. ,  47. , 110. ,  78. ,  52. ,  67. ,  72. ,  79. ,
        70. ,  44. ,  29. ,  42. , 128. ,  83. , 108. ,  40. ,  38. ,
        75. , 158. , 186. , 106. ,  94. , 135. ,  57. ,  89. ,  85. ,
        27. ,  32.5,  46. ,  18. ,  10. ,  80. ,  84. ,  19. , 112. ,
        98. ,  63. ,  74. ,  66. ,  26. ,  55. ,  21. , 118. , 116. ,
        11. , 100. , 165. ,  43. , 125. ,  12. , 295. ,  65. ,  45. ,
        33. ,  71. ,  37. ,  95. , 114. ,  31. , 105. ,  88. ,  99. ,
       300. ,  73. , 150. ])

In [126]:
hankypanky_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [127]:
hankypanky_df.head()

product_name   mrp  price  \
0  Silky 20” A-line Half Slip with Lace  68.0   68.0   
1  Silky 20” A-line Half Slip with Lace  68.0   68.0   
2            Peek-a-Boo Side Tie Bikini  30.0   30.0   
3            Peek-a-Boo Side Tie Bikini  30.0   30.0   
4        All Tied Up Tie Front Bralette  59.0   59.0   

                                             pdp_url  brand_name  \
0  http://www.hankypanky.com/collections/silky-20...  HankyPanky   
1  http://www.hankypanky.com/collections/silky-20...  HankyPanky   
2  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
3  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
4  http://www.hankypanky.com/collections/all-tied...  HankyPanky   

  product_category       retailer  \
0      Collections  Hankypanky US   
1      Collections  Hankypanky US   
2          Panties  Hankypanky US   
3          Panties  Hankypanky US   
4      Collections  Hankypanky US   

                                         description  rating  review_count  \
0  Hanky Panky Silky is the ideal fabric for unde...     NaN           NaN   
1  Hanky Panky Silky is the ideal fabric for unde...     NaN           NaN   
2  Don't go on your honeymoon without this pretty...     NaN           NaN   
3  Don't go on your honeymoon without this pretty...     NaN           NaN   
4                   All Tied Up in ribbons and lace.     NaN           NaN   

                                    style_attributes  \
0  ["Just above-the-knee-length half-slip with el...   
1  ["Just above-the-knee-length half-slip with el...   
2  ["Bikini-style panty in sheer lace ", " Featur...   
3  ["Bikini-style panty in sheer lace ", " Featur...   
4  ["Bralette in scalloped cross-dyed lace", " Fl...   

                       total_sizes                   available_size  \
0  ["Select", "S", "M", "L", "XL"]  ["Select", "S", "M", "L", "XL"]   
1  ["Select", "S", "M", "L", "XL"]  ["Select", "S", "M", "L", "XL"]   
2        ["Select", "S", "M", "L"]        ["Select", "S", "M", "L"]   
3        ["Select", "S", "M", "L"]        ["Select", "S", "M", "L"]   
4       ["Select", "XS", "S", "M"]       ["Select", "XS", "S", "M"]   

         color  
0        Black  
1        Mocha  
2        Black  
3  Light Ivory  
4   Black Plum

In [128]:
hankypanky_df.product_category.unique()

array(['Collections', 'Panties', 'Thongs', 'Lingerie', 'Bras-and-tops'],
      dtype=object)

In [129]:
hankypanky_df[hankypanky_df['product_category'] == 'Bras-and-tops']

product_name   mrp  price  \
96     Signature Lace Short Sleeve Bodysuit  96.0   96.0   
103             Sand Art Crossover Bralette  53.0   53.0   
124                           BARE Bralette  48.0   48.0   
125                           BARE Bralette  48.0   48.0   
126                           BARE Bralette  48.0   48.0   
...                                     ...   ...    ...   
34984                       Cross-Dyed Cami  54.0   54.0   
34990            Sophisticat Retro Bralette  66.0   66.0   
34995     Signature Lace Racerback Bralette  59.0   59.0   
34996     Signature Lace Racerback Bralette  59.0   59.0   
34997     Signature Lace Racerback Bralette  59.0   59.0   

                                                 pdp_url  brand_name  \
96     http://www.hankypanky.com/bras-and-tops/camiso...  HankyPanky   
103    http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
124    http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
125    http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
126    http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
...                                                  ...         ...   
34984  http://www.hankypanky.com/bras-and-tops/camiso...  HankyPanky   
34990  http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
34995  http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
34996  http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   
34997  http://www.hankypanky.com/bras-and-tops/bralet...  HankyPanky   

      product_category       retailer  \
96       Bras-and-tops  Hankypanky US   
103      Bras-and-tops  Hankypanky US   
124      Bras-and-tops  Hankypanky US   
125      Bras-and-tops  Hankypanky US   
126      Bras-and-tops  Hankypanky US   
...                ...            ...   
34984    Bras-and-tops  Hankypanky US   
34990    Bras-and-tops  Hankypanky US   
34995    Bras-and-tops  Hankypanky US   
34996    Bras-and-tops  Hankypanky US   
34997    Bras-and-tops  Hankypanky US   

                                             description  rating  \
96           Work your body in this lacy layering piece.     NaN   
103                                      Life’s a beach.     NaN   
124    Truly-- what to wear when you want to look BARE®.     NaN   
125    Truly-- what to wear when you want to look BARE®.     NaN   
126    Truly-- what to wear when you want to look BARE®.     NaN   
...                                                  ...     ...   
34984  Scalloped lace and color contrast make this de...     NaN   
34990                       The Essential Leopard Print.     NaN   
34995                                       Strap happy.     NaN   
34996                                       Strap happy.     NaN   
34997                                       Strap happy.     NaN   

       review_count                                   style_attributes  \
96              NaN  ["Short sleeve bodysuit in our signature stret...   
103             NaN  ["Soft bralette in our signature stretch lace ...   
124             NaN  ["Made from our unique BARE fabric which offer...   
125             NaN  ["Made from our unique BARE fabric which offer...   
126             NaN  ["Made from our unique BARE fabric which offer...   
...             ...                                                ...   
34984           NaN  ["Unlined cami in our cross-dye lace ", " Scoo...   
34990           NaN  ["Soft bralette in our retro lace ", " No back...   
34995           NaN  ["Soft bralette in our signature stretch lace ...   
34996           NaN  ["Soft bralette in our signature stretch lace ...   
34997           NaN  ["Soft bralette in our signature stretch lace ...   

                       total_sizes               available_size  \
96       ["Select", "S", "M", "L"]    ["Select", "S", "M", "L"]   
103     ["Select", "XS", "S", "M"]   ["Select", "XS", "S", "M"]   
124     ["Select", "XS", "S", "M"]   ["Select

In [130]:
hankypanky_df.shape

(35005, 14)

I feel that I can afford to drop the Bras-and-tops categorized items given the size of this individual dataset. I would like to break this apart in future work on this project. I need to check how many observations are in Collections and Lingerie.

In [131]:
hankypanky_df[hankypanky_df['product_category'] == 'Collections'].shape

(15216, 14)

In [132]:
hankypanky_df[hankypanky_df['product_category'] == 'Lingerie'].shape

(2260, 14)

In [133]:
((2260 + 15216 + 4213)/35005)*100

61.95972003999428

I can still retain 38% of my data by removing items that match the "problem" categories. It may not sound like much, but that is still over 13000 observations so it is worth keeping to work with.

In [134]:
hp_drop_prod_list = ['Bras-and-tops', 'Collections', 'Lingerie']

for i in hp_drop_prod_list:
    hankypanky_df.drop(hankypanky_df[hankypanky_df.product_category == i].index, inplace=True)

In [135]:
hankypanky_df.product_category.unique()

array(['Panties', 'Thongs'], dtype=object)

In [136]:
hankypanky_df['parent_category'] = 'Panties'

In [137]:
hankypanky_df.head()

product_name    mrp  price  \
2                  Peek-a-Boo Side Tie Bikini   30.0   30.0   
3                  Peek-a-Boo Side Tie Bikini   30.0   30.0   
5  30 Pack Original Rise Thongs in Lucite Jar  615.0  615.0   
6            3 Pack Exclusive Low Rise Thongs   64.0   64.0   
7            3 Pack Exclusive Low Rise Thongs   64.0   64.0   

                                             pdp_url  brand_name  \
2  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
3  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
5  http://www.hankypanky.com/thongs/30-pack-origi...  HankyPanky   
6  http://www.hankypanky.com/thongs/3-pack-exclus...  HankyPanky   
7  http://www.hankypanky.com/thongs/3-pack-exclus...  HankyPanky   

  product_category       retailer  \
2          Panties  Hankypanky US   
3          Panties  Hankypanky US   
5           Thongs  Hankypanky US   
6           Thongs  Hankypanky US   
7           Thongs  Hankypanky US   

                                         description  rating  review_count  \
2  Don't go on your honeymoon without this pretty...     NaN           NaN   
3  Don't go on your honeymoon without this pretty...     NaN           NaN   
5  For the ultimate Hanky Panky collector! This l...     NaN           NaN   
6  Exclusively ours. Three thongs in one little p...     NaN           NaN   
7  Exclusively ours. Three thongs in one little p...     NaN           NaN   

                                    style_attributes  \
2  ["Bikini-style panty in sheer lace ", " Featur...   
3  ["Bikini-style panty in sheer lace ", " Featur...   
5  ["One-size thong in our signature stretch lace...   
6  ["Package of three one-size signature stretch ...   
7  ["Package of three one-size signature stretch ...   

                 total_sizes             available_size           color  \
2  ["Select", "S", "M", "L"]  ["Select", "S", "M", "L"]           Black   
3  ["Select", "S", "M", "L"]  ["Select", "S", "M", "L"]     Light Ivory   
5     ["Select", "One Size"]     ["Select", "One Size"]         Rainbow   
6     ["Select", "One Size"]     ["Select", "One Size"]           Aloha   
7     ["Select", "One Size"]     ["Select", "One Size"]  Bermuda Nights   

  parent_category  
2         Panties  
3         Panties  
5         Panties  
6         Panties  
7         Panties

In [138]:
hankypanky_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              9024
review_count        9024
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

In [139]:
hankypanky_df.shape

(13316, 15)

In [140]:
hankypanky_df.review_count.fillna(0, inplace=True)

In [141]:
hankypanky_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              9024
review_count           0
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

In [142]:
hankypanky_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
parent_category      object
dtype: object

In [143]:
hankypanky_df.groupby(['parent_category']).mean()

mrp      price    rating  review_count
parent_category                                              
Panties          35.404701  35.356823  4.869362      1.259087

In [144]:
hankypanky_df.rating.fillna(4.9, inplace=True)

In [145]:
hankypanky_df.head()

product_name    mrp  price  \
2                  Peek-a-Boo Side Tie Bikini   30.0   30.0   
3                  Peek-a-Boo Side Tie Bikini   30.0   30.0   
5  30 Pack Original Rise Thongs in Lucite Jar  615.0  615.0   
6            3 Pack Exclusive Low Rise Thongs   64.0   64.0   
7            3 Pack Exclusive Low Rise Thongs   64.0   64.0   

                                             pdp_url  brand_name  \
2  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
3  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
5  http://www.hankypanky.com/thongs/30-pack-origi...  HankyPanky   
6  http://www.hankypanky.com/thongs/3-pack-exclus...  HankyPanky   
7  http://www.hankypanky.com/thongs/3-pack-exclus...  HankyPanky   

  product_category       retailer  \
2          Panties  Hankypanky US   
3          Panties  Hankypanky US   
5           Thongs  Hankypanky US   
6           Thongs  Hankypanky US   
7           Thongs  Hankypanky US   

                                         description  rating  review_count  \
2  Don't go on your honeymoon without this pretty...     4.9           0.0   
3  Don't go on your honeymoon without this pretty...     4.9           0.0   
5  For the ultimate Hanky Panky collector! This l...     4.9           0.0   
6  Exclusively ours. Three thongs in one little p...     4.9           0.0   
7  Exclusively ours. Three thongs in one little p...     4.9           0.0   

                                    style_attributes  \
2  ["Bikini-style panty in sheer lace ", " Featur...   
3  ["Bikini-style panty in sheer lace ", " Featur...   
5  ["One-size thong in our signature stretch lace...   
6  ["Package of three one-size signature stretch ...   
7  ["Package of three one-size signature stretch ...   

                 total_sizes             available_size           color  \
2  ["Select", "S", "M", "L"]  ["Select", "S", "M", "L"]           Black   
3  ["Select", "S", "M", "L"]  ["Select", "S", "M", "L"]     Light Ivory   
5     ["Select", "One Size"]     ["Select", "One Size"]         Rainbow   
6     ["Select", "One Size"]     ["Select", "One Size"]           Aloha   
7     ["Select", "One Size"]     ["Select", "One Size"]  Bermuda Nights   

  parent_category  
2         Panties  
3         Panties  
5         Panties  
6         Panties  
7         Panties

In [146]:
hankypanky_df.isnull().sum()

product_name        0
mrp                 0
price               0
pdp_url             0
brand_name          0
product_category    0
retailer            0
description         0
rating              0
review_count        0
style_attributes    0
total_sizes         0
available_size      0
color               0
parent_category     0
dtype: int64

### Macy's

In [324]:
macy_df = pd.read_csv('macys_com.csv')

macy_df.head()

product_name      mrp    price  \
0                            ID String Bikini QF1754  $20.00   $20.00    
1                            ID String Bikini QF1754  $20.00   $20.00    
2                            ID String Bikini QF1754  $20.00   $20.00    
3  CK Black Collection Embrace Lace-Waist Thong Q...  $26.00   $26.00    
4                          Halo Lace Boyshort 870205  $15.00   $15.00    

                                             pdp_url    brand_name  \
0  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
1  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
2  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
3  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
4  http://www1.macys.com/shop/product/wacoal-halo...        Wacoal   

                                   product_category  retailer  \
0  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
1  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
2  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
3  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
4  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   

                                         description  rating  review_count  \
0  The perfect amount of coverage in a subtle sil...     NaN           NaN   
1  The perfect amount of coverage in a subtle sil...     NaN           NaN   
2  The perfect amount of coverage in a subtle sil...     NaN           NaN   
3  Exquisitely designed embroidered lace beautifu...     NaN           NaN   
4  A fit that is heavenly. The stretch lace Halo ...     5.0           2.0   

                                    style_attributes  \
0  ["Thin elastic waistband ", "Repeating logo at...   
1  ["Thin elastic waistband ", "Repeating logo at...   
2  ["Thin elastic waistband ", "Repeating logo at...   
3  ["Elastic lace waistband", "Lace at front and ...   
4  ["Stretch lace waistband", "All-over floral la...   

                   total_sizes               available_size          color  
0  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]          Black  
1  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]    Simple Grid  
2  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]          White  
3                        ["M"]                        ["M"]  Regal Sensous  
4        ["S", "M", "L", "XL"]        ["S", "M", "L", "XL"]          Black

In [325]:
macy_df.shape

(40897, 14)

In [326]:
macy_df.isnull().sum()

product_name            0
mrp                     0
price                   0
pdp_url                 0
brand_name              0
product_category        0
retailer                0
description             0
rating              14805
review_count        14796
style_attributes        0
total_sizes             0
available_size          0
color                   0
dtype: int64

In [327]:
macy_df.review_count.unique()

array([ nan,   2.,   1.,  16.,  75.,   4.,  43.,  66., 217.,  33.,   3.,
         6.,   8.,  13., 178.,  11.,  53.,  27.,   7.,  31.,  22.,  20.,
        25.,   5.,  29., 105.,  12.,  79., 125.,  62.,  68.,  21., 406.,
         9.,  48., 167.,  23.,  65.,  26., 198., 147.,  41.,  40., 127.,
        17., 245.,  69.,  14.,  58., 287.,  19.,  18., 172.,  15., 137.,
       188.,  89., 129.,  51.,  59., 141.,  77.,  93., 220., 163.,  47.,
       354., 405.,  10., 114.,  78., 404., 126.,  46., 166.,  76., 286.,
        52.,  88.,  57., 162., 218.,  28.,  50.,  24., 136., 402., 187.,
        87., 161.,  64.,  45., 140., 124., 128., 160.,  32., 158., 135.,
       401.,  37., 305., 123.,  94., 139., 400., 244.,  96.,  86., 134.,
       186.,  73., 399.,  97.])

In [328]:
macy_df.review_count.fillna(0, inplace=True)

In [329]:
macy_df.isnull().sum()

product_name            0
mrp                     0
price                   0
pdp_url                 0
brand_name              0
product_category        0
retailer                0
description             0
rating              14805
review_count            0
style_attributes        0
total_sizes             0
available_size          0
color                   0
dtype: int64

In [330]:
macy_df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [331]:
macy_df.mrp.unique()

array(['$20.00 ', '$26.00 ', '$15.00 ', '$67.00 ', '$46.00 ', '$60.00 ',
       '$48.00 ', '$30.00 ', '$79.00 ', '$78.00 ', '$44.00 ', '$65.00 ',
       '$38.00 ', '$40.00 ', '$22.00 ', '$34.00 ', '$68.00 ', '$32.00 ',
       '$62.00 ', '$35.00 ', '$45.00 ', '$13.00 ', '$12.00 ', '$52.00 ',
       '$55.00 ', '$21.00 ', '$18.00 ', '$56.00 ', '$36.00 ', '$23.00 ',
       '$50.00 ', '$90.00 ', '$25.00 ', '$33.00 ', '$42.00 ', '$54.00 ',
       '$24.98 ', '$53.00 ', '$59.00 ', '$69.00 ', '$108.00 ', '$27.00 ',
       '$63.00 ', '$24.00 ', '$39.00 ', '$72.00 ', '$28.00 ', '$84.00 ',
       '$64.00 ', '$98.00 ', '$125.00 ', '$110.00 ', '$31.00 ', '$58.00 ',
       '$19.00 ', '$85.00 ', '$86.00 ', '$49.00 ', '$135.00 ', '$120.00 ',
       '$96.00 ', '$14.00 ', '$11.50 ', '$29.98 ', '$16.00 ', '$10.00 ',
       '$37.00 ', '$29.00 ', '$19.50 ', '$74.00 ', '$92.00 ', '$104.00 ',
       '$57.00 ', '$88.00 ', '$82.00 ', '$32.50 ', '$43.00 ', '$11.00 '],
      dtype=object)

In [332]:
macy_df.mrp = macy_df.mrp.str.strip('$').str.strip(' ').astype(float)

In [333]:
macy_df.mrp.unique()

array([ 20.  ,  26.  ,  15.  ,  67.  ,  46.  ,  60.  ,  48.  ,  30.  ,
        79.  ,  78.  ,  44.  ,  65.  ,  38.  ,  40.  ,  22.  ,  34.  ,
        68.  ,  32.  ,  62.  ,  35.  ,  45.  ,  13.  ,  12.  ,  52.  ,
        55.  ,  21.  ,  18.  ,  56.  ,  36.  ,  23.  ,  50.  ,  90.  ,
        25.  ,  33.  ,  42.  ,  54.  ,  24.98,  53.  ,  59.  ,  69.  ,
       108.  ,  27.  ,  63.  ,  24.  ,  39.  ,  72.  ,  28.  ,  84.  ,
        64.  ,  98.  , 125.  , 110.  ,  31.  ,  58.  ,  19.  ,  85.  ,
        86.  ,  49.  , 135.  , 120.  ,  96.  ,  14.  ,  11.5 ,  29.98,
        16.  ,  10.  ,  37.  ,  29.  ,  19.5 ,  74.  ,  92.  , 104.  ,
        57.  ,  88.  ,  82.  ,  32.5 ,  43.  ,  11.  ])

In [334]:
macy_df.head()

product_name   mrp    price  \
0                            ID String Bikini QF1754  20.0  $20.00    
1                            ID String Bikini QF1754  20.0  $20.00    
2                            ID String Bikini QF1754  20.0  $20.00    
3  CK Black Collection Embrace Lace-Waist Thong Q...  26.0  $26.00    
4                          Halo Lace Boyshort 870205  15.0  $15.00    

                                             pdp_url    brand_name  \
0  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
1  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
2  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
3  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
4  http://www1.macys.com/shop/product/wacoal-halo...        Wacoal   

                                   product_category  retailer  \
0  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
1  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
2  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
3  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
4  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   

                                         description  rating  review_count  \
0  The perfect amount of coverage in a subtle sil...     NaN           0.0   
1  The perfect amount of coverage in a subtle sil...     NaN           0.0   
2  The perfect amount of coverage in a subtle sil...     NaN           0.0   
3  Exquisitely designed embroidered lace beautifu...     NaN           0.0   
4  A fit that is heavenly. The stretch lace Halo ...     5.0           2.0   

                                    style_attributes  \
0  ["Thin elastic waistband ", "Repeating logo at...   
1  ["Thin elastic waistband ", "Repeating logo at...   
2  ["Thin elastic waistband ", "Repeating logo at...   
3  ["Elastic lace waistband", "Lace at front and ...   
4  ["Stretch lace waistband", "All-over floral la...   

                   total_sizes               available_size          color  
0  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]          Black  
1  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]    Simple Grid  
2  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]          White  
3                        ["M"]                        ["M"]  Regal Sensous  
4        ["S", "M", "L", "XL"]        ["S", "M", "L", "XL"]          Black

In [335]:
macy_df.price.unique()

array(['$20.00 ', '$26.00 ', '$15.00 ', '$67.00 ', '$46.00 ', '$60.00 ',
       '$48.00 ', '$30.00 ', '$79.00 ', '$25.87 ', '$78.00 ', '$24.75 ',
       '$65.00 ', '$21.37 ', '$40.00 ', '$12.37 ', '$45.50 ', '$34.00 ',
       '$47.60 ', '$18.00 ', '$62.00 ', '$35.00 ', '$32.00 ', '$24.99 ',
       '$13.00 ', '$26.60 ', '$45.00 ', '$38.00 ', '$25.50 ', '$12.00 ',
       '$52.00 ', '$38.50 ', '$14.70 ', '$56.00 ', '$22.00 ', '$36.00 ',
       '$23.00 ', '$50.00 ', '$90.00 ', '$25.00 ', '$33.00 ', '$22.50 ',
       '$44.00 ', '$42.00 ', '$54.00 ', '$24.98 ', '$11.25 ', '$53.00 ',
       '$59.00 ', '$68.00 ', '$69.00 ', '$108.00 ', '$27.00 ', '$23.80 ',
       '$63.00 ', '$24.00 ', '$39.00 ', '$72.00 ', '$15.75 ', '$84.00 ',
       '$28.00 ', '$98.00 ', '$125.00 ', '$77.00 ', '$20.25 ', '$31.00 ',
       '$58.00 ', '$55.00 ', '$26.50 ', '$43.87 ', '$22.13 ', '$19.00 ',
       '$7.31 ', '$33.60 ', '$9.75 ', '$85.00 ', '$54.60 ', '$16.80 ',
       '$39.20 ', '$40.60 ', '$33.50 ', '$23.62 ', 

In [336]:
macy_df.price = macy_df.price.str.strip('$').str.strip(' ').astype(float)

macy_df.head()

product_name   mrp  price  \
0                            ID String Bikini QF1754  20.0   20.0   
1                            ID String Bikini QF1754  20.0   20.0   
2                            ID String Bikini QF1754  20.0   20.0   
3  CK Black Collection Embrace Lace-Waist Thong Q...  26.0   26.0   
4                          Halo Lace Boyshort 870205  15.0   15.0   

                                             pdp_url    brand_name  \
0  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
1  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
2  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
3  http://www1.macys.com/shop/product/calvin-klei...  Calvin Klein   
4  http://www1.macys.com/shop/product/wacoal-halo...        Wacoal   

                                   product_category  retailer  \
0  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
1  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
2  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
3  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   
4  Women - Lingerie & Shapewear - Designer Lingerie  Macys US   

                                         description  rating  review_count  \
0  The perfect amount of coverage in a subtle sil...     NaN           0.0   
1  The perfect amount of coverage in a subtle sil...     NaN           0.0   
2  The perfect amount of coverage in a subtle sil...     NaN           0.0   
3  Exquisitely designed embroidered lace beautifu...     NaN           0.0   
4  A fit that is heavenly. The stretch lace Halo ...     5.0           2.0   

                                    style_attributes  \
0  ["Thin elastic waistband ", "Repeating logo at...   
1  ["Thin elastic waistband ", "Repeating logo at...   
2  ["Thin elastic waistband ", "Repeating logo at...   
3  ["Elastic lace waistband", "Lace at front and ...   
4  ["Stretch lace waistband", "All-over floral la...   

                   total_sizes               available_size          color  
0  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]          Black  
1  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]    Simple Grid  
2  ["XS", "S", "M", "L", "XL"]  ["XS", "S", "M", "L", "XL"]          White  
3                        ["M"]                        ["M"]  Regal Sensous  
4        ["S", "M", "L", "XL"]        ["S", "M", "L", "XL"]          Black

In [337]:
macy_df.product_category.unique()

array(['Women - Lingerie & Shapewear - Designer Lingerie',
       'Women - Lingerie & Shapewear - Bras',
       'Women - Lingerie & Shapewear - Sexy Lingerie',
       'Women - Lingerie & Shapewear - Bridal Lingerie',
       'Women - Lingerie & Shapewear - Panties',
       'Women - Lingerie & Shapewear - Lingerie Sets'], dtype=object)

In [338]:
prod_cat_list = ['Women - Lingerie & Shapewear - Designer Lingerie',
       'Women - Lingerie & Shapewear - Bras',
       'Women - Lingerie & Shapewear - Sexy Lingerie',
       'Women - Lingerie & Shapewear - Bridal Lingerie',
       'Women - Lingerie & Shapewear - Panties',
       'Women - Lingerie & Shapewear - Lingerie Sets']

In [339]:
for i in prod_cat_list:
    print(i + ': ' + str(macy_df[macy_df['product_category'] == i].shape))

Women - Lingerie & Shapewear - Designer Lingerie: (18893, 14)
Women - Lingerie & Shapewear - Bras: (9300, 14)
Women - Lingerie & Shapewear - Sexy Lingerie: (1856, 14)
Women - Lingerie & Shapewear - Bridal Lingerie: (230, 14)
Women - Lingerie & Shapewear - Panties: (10592, 14)
Women - Lingerie & Shapewear - Lingerie Sets: (26, 14)


I can get around 20000 observations just by digging out the bras and panties.

In [340]:
m_drop_prod_list = ['Women - Lingerie & Shapewear - Designer Lingerie',
       'Women - Lingerie & Shapewear - Sexy Lingerie',
       'Women - Lingerie & Shapewear - Bridal Lingerie',
       'Women - Lingerie & Shapewear - Lingerie Sets']

m_keep_prod_list = ['Women - Lingerie & Shapewear - Bras','Women - Lingerie & Shapewear - Panties',]

for i in m_drop_prod_list:
    macy_df.drop(macy_df[macy_df.product_category == i].index, inplace=True)

In [341]:
m_cat_dict = {'Women - Lingerie & Shapewear - Bras':'Bras','Women - Lingerie & Shapewear - Panties':'Panties'}

macy_df['parent_category'] = macy_df.product_category.map(m_cat_dict)

In [342]:
macy_df.head()

product_name   mrp  price  \
8             Embrace Lace Contour Bra 853191  60.0   60.0   
9             Embrace Lace Contour Bra 853191  60.0   60.0   
14  After Midnight Retro Mesh Bralette 9K7124  67.0   67.0   
15            Ciao Bella Lace Bralette 910244  30.0   30.0   
16            Ciao Bella Lace Bralette 910244  30.0   30.0   

                                              pdp_url           brand_name  \
8   http://www1.macys.com/shop/product/wacoal-embr...               Wacoal   
9   http://www1.macys.com/shop/product/wacoal-embr...               Wacoal   
14  http://www1.macys.com/shop/product/hanky-panky...          Hanky Panky   
15  http://www1.macys.com/shop/product/b.temptd-by...  b.tempt'd by Wacoal   
16  http://www1.macys.com/shop/product/b.temptd-by...  b.tempt'd by Wacoal   

                       product_category  retailer  \
8   Women - Lingerie & Shapewear - Bras  Macys US   
9   Women - Lingerie & Shapewear - Bras  Macys US   
14  Women - Lingerie & Shapewear - Bras  Macys US   
15  Women - Lingerie & Shapewear - Bras  Macys US   
16  Women - Lingerie & Shapewear - Bras  Macys US   

                                          description  rating  review_count  \
8   The latest style from Wacoal's popular Embrace...     4.5          75.0   
9   The latest style from Wacoal's popular Embrace...     4.5          75.0   
14  Own the night in this sexy bralette from Hanky...     5.0           1.0   
15  Exquisite allover lace and scalloped trim come...     5.0           2.0   
16  Exquisite allover lace and scalloped trim come...     5.0           2.0   

                                     style_attributes  \
8   ["Adjustable straps with scalloped edges", "Se...   
9   ["Adjustable straps with scalloped edges", "Se...   
14  ["Unlined, wireless cups", "Non-adjustable mes...   
15  ["Adjustable straps with double straps at the ...   
16  ["Adjustable straps with double straps at the ...   

                                          total_sizes  \
8   ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...   
9   ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...   
14                                   ["XS", "S", "M"]   
15                        ["XS", "S", "M", "L", "XL"]   
16                        ["XS", "S", "M", "L", "XL"]   

                                       available_size                 color  \
8   ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...                 Black   
9   ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...  Naturally Nude/Ivory   
14                                   ["XS", "S", "M"]                 Black   
15                        ["XS", "S", "M", "L", "XL"]          Bridal White   
16                        ["XS", "S", "M", "L", "XL"]         Camellia Rose   

   parent_category  
8             Bras  
9             Bras  
14            Bras  
15            Bras  
16            Bras

In [343]:
macy_df.shape

(19892, 15)

In [344]:
macy_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              6713
review_count           0
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

In [345]:
macy_df.groupby(['parent_category']).mean()

mrp      price    rating  review_count
parent_category                                              
Bras             44.864209  40.151081  4.370564     35.911505
Panties          20.980363  20.111778  4.542329     17.057119

In [346]:
m_rating_dict = {'Bras':4.4, 'Panties':4.5}

In [347]:
macy_df.loc[macy_df['rating'].isnull(),'rating'] = macy_df['parent_category'].map(m_rating_dict)

In [348]:
macy_df.isnull().sum()

product_name        0
mrp                 0
price               0
pdp_url             0
brand_name          0
product_category    0
retailer            0
description         0
rating              0
review_count        0
style_attributes    0
total_sizes         0
available_size      0
color               0
parent_category     0
dtype: int64

In [349]:
macy_df.shape

(19892, 15)

### Nordstrom

In [270]:
nord_df = pd.read_csv('shop_nordstrom_com.csv')

nord_df.head()

product_name      mrp    price  \
0           'B Fitting' High Cut Briefs  $15.00   $15.00    
1           'B Fitting' High Cut Briefs  $15.00   $15.00    
2           'B Fitting' High Cut Briefs  $15.00   $15.00    
3           'B Fitting' High Cut Briefs  $15.00   $15.00    
4  'Skinsense' Seamless High Cut Briefs  $18.00   $18.00    

                                             pdp_url brand_name  \
0  http://shop.nordstrom.com/s/wacoal-b-fitting-h...     WACOAL   
1  http://shop.nordstrom.com/s/wacoal-b-fitting-h...     WACOAL   
2  http://shop.nordstrom.com/s/wacoal-b-fitting-h...     WACOAL   
3  http://shop.nordstrom.com/s/wacoal-b-fitting-h...     WACOAL   
4  http://shop.nordstrom.com/s/wacoal-skinsense-s...     WACOAL   

     product_category      retailer  \
0     Women's Panties  Nordstrom US   
1     Women's Panties  Nordstrom US   
2     Women's Panties  Nordstrom US   
3     Women's Panties  Nordstrom US   
4  Skin-Tone Lingerie  Nordstrom US   

                                         description  rating  review_count  \
0  Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
1  Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
2  Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
3  Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
4  Cleanly finished edges ensure that these full-...     3.0           2.0   

                                    style_attributes  \
0  ["79% Supima® cotton, 21% spandex.", "Hand was...   
1  ["79% Supima® cotton, 21% spandex.", "Hand was...   
2  ["79% Supima® cotton, 21% spandex.", "Hand was...   
3  ["79% Supima® cotton, 21% spandex.", "Hand was...   
4  ["Cotton-lined gusset.", "72% nylon, 28% spand...   

                               total_sizes  \
0                                    [nil]   
1                                    [nil]   
2                                    [nil]   
3                                    [nil]   
4  ["X-Large", "Large", "Medium", "Small"]   

                            available_size  color  
0                                    [nil]  Black  
1                                    [nil]   Nude  
2                                    [nil]  White  
3                                    [nil]   Navy  
4  ["X-Large", "Large", "Medium", "Small"]  Black

In [271]:
print(nord_df.dtypes)
print('---------------')
print(nord_df.shape)
print('---------------')
print(nord_df.isnull().sum())

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object
---------------
(12568, 14)
---------------
product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              4690
review_count        4690
style_attributes       0
total_sizes            0
available_size         0
color                  0
dtype: int64


In [272]:
#macy_df.mrp = macy_df.mrp.str.strip('$').str.strip(' ').astype(float)
nord_df.mrp.unique()

array(['$15.00 ', '$18.00 ', '$23.00 ', '$78.00 ', '$20.00 ', '$90.00 ',
       '$13.00 ', '$70.00 ', '$29.00 ', '$39.00 ', '$22.00 ', '$38.00 ',
       '$55.00 ', '$69.00 ', '$65.00 ', '$43.00 ', '$64.00 ', '$72.00 ',
       '$48.00 ', '$45.00 ', '$19.00 ', '$32.00 ', '$44.00 ', '$68.00 ',
       '$28.00 ', '$62.00 ', '$60.00 ', '$36.00 ', '$35.00 ', '$102.00 ',
       '$82.00 ', '$40.00 ', '$50.00 ', '$46.00 ', '$24.00 ', '$25.00 ',
       '$26.00 ', '$30.00 ', '$42.00 ', '$34.00 ', '$52.00–$56.00',
       '$74.00 ', '$79.00 ', '$58.00 ', '$59.00 ', '$52.00 ', '$54.00 ',
       '$66.00 ', '$100.00 ', '$23.00–$25.00', '$75.00 ', '$56.00 ',
       '$33.00 ', '$135.00 ', '$31.00 ', '$49.00 ', '$63.00 ', '$27.00 ',
       '$96.00 ', '$98.00 ', '$89.00 ', '$57.00 ', '$84.00 ', '$16.00 ',
       '$6.00 '], dtype=object)

In [273]:
nord_df.price.unique()

array(['$15.00 ', '$18.00 ', '$23.00 ', '$78.00 ', '$20.00 ', '$90.00 ',
       '$13.00 ', '$70.00 ', '$29.00 ', '$39.00 ', '$22.00 ', '$38.00 ',
       '$55.00 ', '$69.00 ', '$65.00 ', '$43.00 ', '$64.00 ', '$72.00 ',
       '$48.00 ', '$45.00 ', '$19.00 ', '$32.00 ', '$44.00 ', '$68.00 ',
       '$28.00 ', '$62.00 ', '$60.00 ', '$36.00 ', '$35.00 ', '$102.00 ',
       '$82.00 ', '$40.00 ', '$50.00 ', '$46.00 ', '$24.00 ', '$25.00 ',
       '$26.00 ', '$30.00 ', '$42.00 ', '$34.00 ', '$31.20–$33.60',
       '$11.98 ', '$74.00 ', '$79.00 ', '$58.00 ', '$7.80 ', '$59.00 ',
       '$52.00 ', '$54.00 ', '$13.20 ', '$66.00 ', '$100.00 ', '$22.80 ',
       '$23.00–$25.00', '$23.40 ', '$75.00 ', '$56.00 ', '$33.00 ',
       '$37.20 ', '$26.40 ', '$47.40 ', '$135.00 ', '$16.80 ', '$31.00 ',
       '$49.00 ', '$17.98 ', '$63.00 ', '$21.60 ', '$27.00 ', '$57.60 ',
       '$98.00 ', '$14.98 ', '$89.00 ', '$34.80 ', '$61.20 ', '$29.40 ',
       '$57.00 ', '$84.00 ', '$44.98 ', '$38.40 ', '$19.20 

In [274]:
nord_df.mrp.replace(to_replace=['$52.00–$56.00','$23.00–$25.00'], value=['$56.00', '$25.00'], inplace=True)

In [275]:
nord_df.mrp.unique()

array(['$15.00 ', '$18.00 ', '$23.00 ', '$78.00 ', '$20.00 ', '$90.00 ',
       '$13.00 ', '$70.00 ', '$29.00 ', '$39.00 ', '$22.00 ', '$38.00 ',
       '$55.00 ', '$69.00 ', '$65.00 ', '$43.00 ', '$64.00 ', '$72.00 ',
       '$48.00 ', '$45.00 ', '$19.00 ', '$32.00 ', '$44.00 ', '$68.00 ',
       '$28.00 ', '$62.00 ', '$60.00 ', '$36.00 ', '$35.00 ', '$102.00 ',
       '$82.00 ', '$40.00 ', '$50.00 ', '$46.00 ', '$24.00 ', '$25.00 ',
       '$26.00 ', '$30.00 ', '$42.00 ', '$34.00 ', '$56.00', '$74.00 ',
       '$79.00 ', '$58.00 ', '$59.00 ', '$52.00 ', '$54.00 ', '$66.00 ',
       '$100.00 ', '$25.00', '$75.00 ', '$56.00 ', '$33.00 ', '$135.00 ',
       '$31.00 ', '$49.00 ', '$63.00 ', '$27.00 ', '$96.00 ', '$98.00 ',
       '$89.00 ', '$57.00 ', '$84.00 ', '$16.00 ', '$6.00 '], dtype=object)

In [276]:
nord_df.price.replace(to_replace=['$31.20–$33.60','$23.00–$25.00'], value=['$33.60', '$25.00'], inplace=True)

In [277]:
nord_df.mrp = nord_df.mrp.str.strip('$').str.strip(' ').astype(float)
nord_df.price = nord_df.price.str.strip('$').str.strip(' ').astype(float)

In [278]:
nord_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [279]:
prod_list = list(nord_df.product_category.unique())

for i in prod_list:
    print(i + ': ' + str(nord_df[nord_df['product_category'] == i].shape))
    print('--------------------------')

Women's Panties: (4847, 14)
--------------------------
Skin-Tone Lingerie: (3696, 14)
--------------------------
Sexy Lingerie: (964, 14)
--------------------------
Bras: (2679, 14)
--------------------------
Bridal Lingerie: (382, 14)
--------------------------


In [280]:
nord_df.shape

(12568, 14)

In [281]:
((3696+964+382)/12568)*100

40.11775938892425

I can retain 40% of data by sticking to just bras and panties.

In [282]:
n_drop_prod_list = ['Skin-Tone Lingerie', 'Sexy Lingerie', 'Bridal Lingerie']

for i in n_drop_prod_list:
    nord_df.drop(nord_df[nord_df.product_category == i].index, inplace=True)

In [283]:
nord_df.product_category.unique()

array(["Women's Panties", 'Bras'], dtype=object)

In [284]:
n_prod_dict = {"Women's Panties":'Panties', 'Bras':'Bras'}
nord_df['parent_category'] = nord_df.product_category.map(n_prod_dict)

In [285]:
nord_df.head()

product_name   mrp  price  \
0   'B Fitting' High Cut Briefs  15.0   15.0   
1   'B Fitting' High Cut Briefs  15.0   15.0   
2   'B Fitting' High Cut Briefs  15.0   15.0   
3   'B Fitting' High Cut Briefs  15.0   15.0   
11            'B Sultry' Bikini  20.0   20.0   

                                              pdp_url           brand_name  \
0   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
1   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
2   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
3   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
11  http://shop.nordstrom.com/s/b-temptd-by-wacoal...  B.TEMPT'D BY WACOAL   

   product_category      retailer  \
0   Women's Panties  Nordstrom US   
1   Women's Panties  Nordstrom US   
2   Women's Panties  Nordstrom US   
3   Women's Panties  Nordstrom US   
11  Women's Panties  Nordstrom US   

                                          description  rating  review_count  \
0   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
1   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
2   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
3   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
11  A Chantilly lace front brings French design-in...     NaN           NaN   

                                     style_attributes  \
0   ["79% Supima® cotton, 21% spandex.", "Hand was...   
1   ["79% Supima® cotton, 21% spandex.", "Hand was...   
2   ["79% Supima® cotton, 21% spandex.", "Hand was...   
3   ["79% Supima® cotton, 21% spandex.", "Hand was...   
11  ["Stretch mesh body.", "Chantilly lace front."...   

                                total_sizes  \
0                                     [nil]   
1                                     [nil]   
2                                     [nil]   
3                                     [nil]   
11  ["X-Large", "Small", "Medium", "Large"]   

                             available_size                     color  \
0                                     [nil]                     Black   
1                                     [nil]                      Nude   
2                                     [nil]                     White   
3                                     [nil]                      Navy   
11  ["X-Large", "Small", "Large", "Medium"]  Vanilla Ice/ Peach Beige   

   parent_category  
0          Panties  
1          Panties  
2          Panties  
3          Panties  
11         Panties

In [286]:
nord_df.isnull().sum()

product_name           0
mrp                    0
price                  0
pdp_url                0
brand_name             0
product_category       0
retailer               0
description            0
rating              3116
review_count        3116
style_attributes       0
total_sizes            0
available_size         0
color                  0
parent_category        0
dtype: int64

In [287]:
nord_df.head()

product_name   mrp  price  \
0   'B Fitting' High Cut Briefs  15.0   15.0   
1   'B Fitting' High Cut Briefs  15.0   15.0   
2   'B Fitting' High Cut Briefs  15.0   15.0   
3   'B Fitting' High Cut Briefs  15.0   15.0   
11            'B Sultry' Bikini  20.0   20.0   

                                              pdp_url           brand_name  \
0   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
1   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
2   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
3   http://shop.nordstrom.com/s/wacoal-b-fitting-h...               WACOAL   
11  http://shop.nordstrom.com/s/b-temptd-by-wacoal...  B.TEMPT'D BY WACOAL   

   product_category      retailer  \
0   Women's Panties  Nordstrom US   
1   Women's Panties  Nordstrom US   
2   Women's Panties  Nordstrom US   
3   Women's Panties  Nordstrom US   
11  Women's Panties  Nordstrom US   

                                          description  rating  review_count  \
0   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
1   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
2   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
3   Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
11  A Chantilly lace front brings French design-in...     NaN           NaN   

                                     style_attributes  \
0   ["79% Supima® cotton, 21% spandex.", "Hand was...   
1   ["79% Supima® cotton, 21% spandex.", "Hand was...   
2   ["79% Supima® cotton, 21% spandex.", "Hand was...   
3   ["79% Supima® cotton, 21% spandex.", "Hand was...   
11  ["Stretch mesh body.", "Chantilly lace front."...   

                                total_sizes  \
0                                     [nil]   
1                                     [nil]   
2                                     [nil]   
3                                     [nil]   
11  ["X-Large", "Small", "Medium", "Large"]   

                             available_size                     color  \
0                                     [nil]                     Black   
1                                     [nil]                      Nude   
2                                     [nil]                     White   
3                                     [nil]                      Navy   
11  ["X-Large", "Small", "Large", "Medium"]  Vanilla Ice/ Peach Beige   

   parent_category  
0          Panties  
1          Panties  
2          Panties  
3          Panties  
11         Panties

In [288]:
nord_df.shape

(7526, 15)

In [289]:
nord_df.review_count.fillna(0, inplace=True)

In [290]:
nord_df.groupby(['parent_category']).mean()

mrp      price    rating  review_count
parent_category                                              
Bras             48.349384  45.835461  4.280933     55.841732
Panties          24.444811  23.407795  4.423918     21.043119

In [350]:
n_rating_dict = {'Bras':4.3, 'Panties':4.4}

nord_df.loc[nord_df['rating'].isnull(),'rating'] = nord_df['parent_category'].map(n_rating_dict)

In [351]:
nord_df.isnull().sum()

product_name        0
mrp                 0
price               0
pdp_url             0
brand_name          0
product_category    0
retailer            0
description         0
rating              0
review_count        0
style_attributes    0
total_sizes         0
available_size      0
color               0
parent_category     0
dtype: int64

### Topshop

In [352]:
ts_df = pd.read_csv('us_topshop_com.csv')

ts_df.head()

product_name      mrp    price  \
0  MATERNITY Criss Cross Knickers   $20.00   $20.00   
1        Floral Lace Triangle Bra   $35.00   $35.00   
2               Floral Lace Thong   $20.00   $20.00   
3            Mesh French Knickers   $10.00   $10.00   
4               Floral Lace Thong   $10.00   $10.00   

                                             pdp_url  brand_name  \
0  http://www.topshop.com/en/tsus/product/clothin...  US TOPSHOP   
1  http://www.topshop.com/en/tsus/product/clothin...  US TOPSHOP   
2  http://www.topshop.com/en/tsus/product/clothin...  US TOPSHOP   
3  http://www.topshop.com/en/tsus/product/clothin...  US TOPSHOP   
4  http://www.topshop.com/en/tsus/product/clothin...  US TOPSHOP   

  product_category    retailer  \
0         Lingerie  Topshop US   
1         Lingerie  Topshop US   
2         Lingerie  Topshop US   
3         Lingerie  Topshop US   
4         Lingerie  Topshop US   

                                         description  rating  review_count  \
0  These feminine black knickers for maternity fe...     NaN           NaN   
1  In an appealing burnt orange tint, this low ri...     NaN           NaN   
2  In an appealing burnt orange tint, this low ri...     NaN           NaN   
3  Indulge your playful side with these sheer mes...     NaN           NaN   
4  Keep slinky silhouettes seam-free with this la...     3.0           1.0   

   style_attributes       total_sizes available_size      color  
0               NaN       4,6,8,10,12    4,6,8,10,12      BLACK  
1               NaN     2,4,6,8,10,12      2,8,10,12        NaN  
2               NaN     2,4,6,8,10,12  2,4,6,8,10,12        NaN  
3               NaN  2,4,6,8,10,12,14      4,6,10,12  RASPBERRY  
4               NaN     2,4,6,8,10,12  2,4,6,8,10,12      BLACK

In [353]:
ts_df.shape

(3082, 14)

In [354]:
ts_df.mrp.unique()

array(['\xa0$20.00', '\xa0$35.00', '\xa0$10.00', '\xa0$45.00',
       '\xa0$30.00', '\xa0$15.00', '\xa0$36.00', '\xa0$12.00',
       '\xa0$40.00', '\xa0$22.00', '\xa0$52.00', '\xa0$8.00',
       '\xa0$26.00', '\xa0$38.00',
       '\xa0$35.00\n\t\t\t\t\t            \t\t\t\t\t\t\t\t            \t\t\t\t\t            \t\t\t\n\t\t\t\t\t            \t\t\n\t\t\t\t\t\t            \t\t\t\tNow\xa0$10.00',
       '\xa0$70.00', '\xa0$28.00', '\xa0$90.00', '\xa0$60.00',
       '\xa0$35.00\n\t\t\t\t\t            \t\t\t\t\t\t\t\t            \t\t\t\t\t            \t\t\t\n\t\t\t\t\t            \t\t\n\t\t\t\t\t\t            \t\t\t\tNow\xa0$20.00',
       '\xa0$15.00\n\t\t\t\t\t            \t\t\t\t\t\t\t\t            \t\t\t\t\t            \t\t\t\n\t\t\t\t\t            \t\t\n\t\t\t\t\t\t            \t\t\t\tNow\xa0$8.00',
       '\xa0$110.00',
       '\xa0$38.00\n\t\t\t\t\t            \t\t\t\t\t\t\t\t            \t\t\t\t\t            \t\t\t\n\t\t\t\t\t            \t\t\n\t\t\t\t\t\t            \t\t\t\tNow\x

In [355]:
ts_df.product_category.unique()

array(['Lingerie'], dtype=object)

Leaving topshop out because it is only categorized as lingerie.

### Victoria's Secret

In [356]:
vs_df = pd.read_csv('victoriassecret_com.csv')

vs_df.head()

product_name      mrp    price  \
0  Very Sexy Strappy Lace Thong Panty  $14.50   $14.50    
1  Very Sexy Strappy Lace Thong Panty  $14.50   $14.50    
2  Very Sexy Strappy Lace Thong Panty  $14.50   $14.50    
3  Very Sexy Strappy Lace Thong Panty  $14.50   $14.50    
4  Very Sexy Strappy Lace Thong Panty  $14.50   $14.50    

                                             pdp_url         brand_name  \
0  https://www.victoriassecret.com/panties/shop-a...  Victoria's Secret   
1  https://www.victoriassecret.com/panties/shop-a...  Victoria's Secret   
2  https://www.victoriassecret.com/panties/shop-a...  Victoria's Secret   
3  https://www.victoriassecret.com/panties/shop-a...  Victoria's Secret   
4  https://www.victoriassecret.com/panties/shop-a...  Victoria's Secret   

           product_category            retailer  \
0  Strappy Lace Thong Panty  Victoriassecret US   
1  Strappy Lace Thong Panty  Victoriassecret US   
2  Strappy Lace Thong Panty  Victoriassecret US   
3  Strappy Lace Thong Panty  Victoriassecret US   
4  Strappy Lace Thong Panty  Victoriassecret US   

                                         description  rating  review_count  \
0  Lots of cheek peek, pretty lace, a strappy bac...     NaN           NaN   
1  Lots of cheek peek, pretty lace, a strappy bac...     NaN           NaN   
2  Lots of cheek peek, pretty lace, a strappy bac...     NaN           NaN   
3  Lots of cheek peek, pretty lace, a strappy bac...     NaN           NaN   
4  Lots of cheek peek, pretty lace, a strappy bac...     NaN           NaN   

   style_attributes                  total_sizes available_size        color  
0               NaN  ["XS", "S", "M", "L", "XL"]              S  peach melba  
1               NaN  ["XS", "S", "M", "L", "XL"]              S        black  
2               NaN  ["XS", "S", "M", "L", "XL"]              S    plum dust  
3               NaN  ["XS", "S", "M", "L", "XL"]              S  ensign blue  
4               NaN  ["XS", "S", "M", "L", "XL"]              S  fair orchid

In [357]:
vs_df.mrp.unique()

array(['$14.50 ', '$15.00 ', '$20.00 ', '$16.50 ', '$10.50 ', '$54.50 ',
       '$38.50 ', '$34.50 ', '$29.50 ', '$98.00 ', '$24.50 ', '$49.50 ',
       '$52.50 ', '$58.50 ', '$64.50 ', '$68.50 ', '$36.50 ', '$34.95 ',
       '$35.00 ', '$39.50 ', '$32.50 ', '$78.00 ', '$49.95 ', '$32.95 ',
       '$48.00 ', '$68.00 ', '$8.50 ', '$36.95 ', '$22.95 ', '$24.95 ',
       '$44.50 ', '$42.00 ', '$62.50 ', '$42.50 ', '$58.00 ', '$52.00 ',
       '$26.95 ', '$59.50 ', '$55.50 ', '$25.00 ', '$38.00 ', '$40.00 ',
       '$36.00 ', '$45.00 ', '$66.50 ', '$9.95 ', '$46.50 ', '$42.95 ',
       '$39.95 ', '$62.00 ', '$48.50 ', '$56.50 ', '$54.95 ', '$24.00 ',
       '$28.00 ', '$29.95 ', '$54.00 ', '$32.00 ', '$12.95 ', '$28.95 ',
       '$30.00 ', '$34.00 ', '$69.50 ', '$44.95 ', '$12.50 ', '$22.50 ',
       '₡24.769', '₡25.935', 'Rp721.448', '$59.95 ', '$27.95 ', '$26.50 ',
       '$16.95 ', '$64.95 ', '$48.95 ', 'Rp116.911', 'Rp474.522',
       'Rp543.294'], dtype=object)

In [358]:
vs_df.price.unique()

array(['$14.50 ', '$15.00 ', '$20.00 ', '$16.50 ', '$10.50 ', '$19.99 ',
       '$4.99 ', '$38.50 ', '$34.50 ', '$29.50 ', '$98.00 ', '$24.50 ',
       '$24.99 ', '$49.50 ', '$52.50 ', '$58.50 ', '$54.50 ', '$9.99 ',
       '$64.50 ', '$68.50 ', '$36.50 ', '$34.95 ', '$17.99 ', '$14.99 ',
       '$7.99 ', '$78.00 ', '$49.95 ', '$3.99 ', '$32.95 ', '$48.00 ',
       '$68.00 ', '$8.50 ', '$36.95 ', '$22.95 ', '$24.95 ', '$42.00 ',
       '$29.99 ', '$42.50 ', '$39.50 ', '$58.00 ', '$52.00 ', '$26.95 ',
       '$59.50 ', '$62.50 ', '$32.50 ', '$55.50 ', '$25.00 ', '$44.50 ',
       '$38.00 ', '$40.00 ', '$36.00 ', '$45.00 ', '$16.99 ', '$66.50 ',
       '$5.99 ', '$9.95 ', '$42.95 ', '$39.95 ', '$62.00 ', '$56.50 ',
       '$46.50 ', '$54.95 ', '$24.00 ', '$48.50 ', '$28.00 ', '$12.99 ',
       '$54.00 ', '$32.00 ', '$2.99 ', '$12.95 ', '$28.95 ', '$30.00 ',
       '$34.00 ', '$69.50 ', '$44.95 ', '$34.99 ', '$21.99 ', '$39.99 ',
       '₡24.769', '₡25.935', '$5.00 ', 'Rp412.118', '$59.95

I'm not going to convert the different currency at this stage, but I'm possibly going to remove incorrect currency styles.

In [359]:
mrp_drop_list = ['₡24.769', '₡25.935', 'Rp721.448', 'Rp116.911', 'Rp474.522', 'Rp543.294']

price_drop_list = ['₡24.769', '₡25.935', 'Rp412.118', 'Rp116.911', 'Rp474.522', 'Rp543.294', 'Rp343.857']

In [365]:
for i in mrp_drop_list:
    vs_df.drop(vs_df[vs_df.mrp == i].index, inplace=True)

In [366]:
for i in price_drop_list:
    vs_df.drop(vs_df[vs_df.price == i].index, inplace=True)

In [367]:
vs_df.shape

(452880, 14)

In [368]:
vs_df.mrp.unique()

array(['$14.50 ', '$15.00 ', '$20.00 ', '$16.50 ', '$10.50 ', '$54.50 ',
       '$38.50 ', '$34.50 ', '$29.50 ', '$98.00 ', '$24.50 ', '$49.50 ',
       '$52.50 ', '$58.50 ', '$64.50 ', '$68.50 ', '$36.50 ', '$34.95 ',
       '$35.00 ', '$39.50 ', '$32.50 ', '$78.00 ', '$49.95 ', '$32.95 ',
       '$48.00 ', '$68.00 ', '$8.50 ', '$36.95 ', '$22.95 ', '$24.95 ',
       '$44.50 ', '$42.00 ', '$62.50 ', '$42.50 ', '$58.00 ', '$52.00 ',
       '$26.95 ', '$59.50 ', '$55.50 ', '$25.00 ', '$38.00 ', '$40.00 ',
       '$36.00 ', '$45.00 ', '$66.50 ', '$9.95 ', '$46.50 ', '$42.95 ',
       '$39.95 ', '$62.00 ', '$48.50 ', '$56.50 ', '$54.95 ', '$24.00 ',
       '$28.00 ', '$29.95 ', '$54.00 ', '$32.00 ', '$12.95 ', '$28.95 ',
       '$30.00 ', '$34.00 ', '$69.50 ', '$44.95 ', '$12.50 ', '$22.50 ',
       '$59.95 ', '$27.95 ', '$26.50 ', '$16.95 ', '$64.95 ', '$48.95 '],
      dtype=object)

In [369]:
vs_df.mrp = vs_df.mrp.str.strip('$').str.strip(' ').astype(float)
vs_df.price = vs_df.price.str.strip('$').str.strip(' ').astype(float)

In [370]:
vs_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes    float64
total_sizes          object
available_size       object
color                object
dtype: object

In [371]:
vs_df.price.unique()

array([14.5 , 15.  , 20.  , 16.5 , 10.5 , 19.99,  4.99, 38.5 , 34.5 ,
       29.5 , 98.  , 24.5 , 24.99, 49.5 , 52.5 , 58.5 , 54.5 ,  9.99,
       64.5 , 68.5 , 36.5 , 34.95, 17.99, 14.99,  7.99, 78.  , 49.95,
        3.99, 32.95, 48.  , 68.  ,  8.5 , 36.95, 22.95, 24.95, 42.  ,
       29.99, 42.5 , 39.5 , 58.  , 52.  , 26.95, 59.5 , 62.5 , 32.5 ,
       55.5 , 25.  , 44.5 , 38.  , 40.  , 36.  , 45.  , 16.99, 66.5 ,
        5.99,  9.95, 42.95, 39.95, 62.  , 56.5 , 46.5 , 54.95, 24.  ,
       48.5 , 28.  , 12.99, 54.  , 32.  ,  2.99, 12.95, 28.95, 30.  ,
       34.  , 69.5 , 44.95, 34.99, 21.99, 39.99,  5.  , 59.95, 27.95,
       22.5 , 23.99, 35.99, 16.95, 64.95, 48.95, 29.95, 32.99])

In [372]:
vs_df.style_attributes = vs_df.style_attributes.astype(str)

In [373]:
vs_df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes     object
total_sizes          object
available_size       object
color                object
dtype: object

In [374]:
vs_df.isnull().sum()

product_name             0
mrp                      0
price                    0
pdp_url                  0
brand_name               0
product_category         0
retailer                 0
description              0
rating              315380
review_count        315380
style_attributes         0
total_sizes              0
available_size           0
color                    0
dtype: int64

In [375]:
vs_df.shape

(452880, 14)

In [376]:
vs_df.review_count.fillna(0, inplace=True)

In [377]:
vs_df.isnull().sum()

product_name             0
mrp                      0
price                    0
pdp_url                  0
brand_name               0
product_category         0
retailer                 0
description              0
rating              315380
review_count             0
style_attributes         0
total_sizes              0
available_size           0
color                    0
dtype: int64

In [378]:
vs_df.product_category.unique()

array(['Strappy Lace Thong Panty',
       'The Player by Victoria Sport Sport Bra',
       'Lace Cutout Thong Panty', 'Lace Back No-Show Thong', 'Demi Bra',
       'Lace Shortie Panty', 'The Wicked Unlined Uplift Bra',
       'Lightweight by Victoria Sport Strappy Sport Bra',
       'Fishnet Lace Kimono', 'Push-Up Bralette', 'Push-Up Bra',
       'Add-1½-Cups Push-Up Bra', 'Mesh Front-close Bralette',
       'Cutout High-neck Bralette', 'Strappy Push-Up Bra',
       'Knockout by Victoria Sport Front-Close Sport Bra',
       'Front-close Bralette', 'Mini Lace Bustier',
       'Seamless High-neck Sport Bra', 'Lace Long Line Bra',
       'Strappy Bandeau Top', 'Incredible by Victoria Sport Bra',
       'Unlined Demi Bra', 'Lace-trim Hipkini Panty',
       'Lace-trim Hiphugger Panty', 'Lace-up Bodysuit',
       'High Leg One-Piece', 'Pineapple Cheekini Panty',
       'Wear Everywhere Super Push', 'Satin & Lace Mini Slip',
       'Lace-trim High-leg Brief Panty', 'Strappy V-neck Teddy',
   

### Combining Necessary DFs

In [379]:
ae_df.head(2)

product_name   mrp  price  \
0  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
1  Aerie Everyday Loves Lace Cheeky  12.5   12.5   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0             8   
1  Introducing Everyday Loves™: Made with love. E...     5.0             8   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color parent_category  
0  Rugged Green         Panties  
1  Natural Nude         Panties

In [380]:
amz_df.head(2)

product_name   mrp  price  \
0  Calvin Klein Women's Sheer Marquisette Demi Un...  36.0   32.4   
1                   Wacoal Embrace Lace Bikini Panty  27.0   27.0   

                                             pdp_url    brand_name  \
0  https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1  Calvin-Klein   
1  https://www.amazon.com/-/dp/B0011YQFNK?th=1&psc=1        Wacoal   

  product_category   retailer  \
0             Bras  Amazon US   
1          Panties  Amazon US   

                                         description  rating  review_count  \
0  An unlined demi cup bra featuring sheer, sexy ...     4.5            47   
1  Embrace lace bikini offers great fit and match...     4.4            91   

                                    style_attributes  \
0  [ 72% Nylon, 28% Elastane , Imported , hook an...   
1  [ 100% Nylon , Imported , Hand Wash , 1.2" hig...   

                                         total_sizes  \
0  30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...   
1                   Small , Medium , Large , X-Large   

                                      available_size  color parent_category  
0  30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...   Bare            Bras  
1                           Small , Medium , X-Large  Large         Panties

In [381]:
btd_df.head(2)

product_name   mrp  price  \
11  b.splendid Underwire T-shirt Bra  44.0   44.0   
12  b.splendid Underwire T-shirt Bra  44.0   44.0   

                                              pdp_url brand_name  \
11  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   
12  http://btemptd.wacoal-america.com/b-splendid-u...     WACOAL   

      product_category    retailer  \
11  BRAS AND BRALETTES  Btemptd US   
12  BRAS AND BRALETTES  Btemptd US   

                                          description  rating  review_count  \
11  With underwire concealed between layers of foa...     NaN           0.0   
12  With underwire concealed between layers of foa...     NaN           0.0   

                                     style_attributes  \
11  [Underwire t-shirt bra,Stretch foam cups,Soft ...   
12  [Underwire t-shirt bra,Stretch foam cups,Soft ...   

                                          total_sizes  \
11  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   
12  30C,30D,30DD,30DDD,32A,32B,32C,32D,32DD,32DDD,...   

                                       available_size                   color  \
11  30c,30d,30dd,32b,32c,32d,32dd,32ddd,34a,34b,34...  Cherry Blossom Heather   
12  36d,30c,30d,30dd,30ddd,32a,32b,32c,32d,32dd,32...           Pansy Heather   

   parent_category  
11            Bras  
12            Bras

In [382]:
ck_df.head(2)

product_name   mrp  price  \
0  logo cotton stretch thong  13.0   13.0   
1  logo cotton stretch thong  13.0   13.0   

                                             pdp_url    brand_name  \
0  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   
1  http://www.calvinklein.us/en/womens-clothing/w...  Calvin Klein   

            product_category         retailer  \
0  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   
1  3 FOR 33 PANTY ESSENTIALS  Calvin Klein US   

                                         description  rating  review_count  \
0  soft cotton stretch fabric and a metallic logo...     NaN           0.0   
1  soft cotton stretch fabric and a metallic logo...     NaN           0.0   

                                    style_attributes total_sizes  \
0  ["cotton stretch thong panty","metallic elasti...       s,m,l   
1  ["cotton stretch thong panty","metallic elasti...       s,m,l   

  available_size         color parent_category  
0          s,m,l         BLACK         Panties  
1          s,m,l  ASHFORD GREY         Panties

In [383]:
hankypanky_df.head(2)

product_name   mrp  price  \
2  Peek-a-Boo Side Tie Bikini  30.0   30.0   
3  Peek-a-Boo Side Tie Bikini  30.0   30.0   

                                             pdp_url  brand_name  \
2  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   
3  http://www.hankypanky.com/panties/bridal-peek-...  HankyPanky   

  product_category       retailer  \
2          Panties  Hankypanky US   
3          Panties  Hankypanky US   

                                         description  rating  review_count  \
2  Don't go on your honeymoon without this pretty...     4.9           0.0   
3  Don't go on your honeymoon without this pretty...     4.9           0.0   

                                    style_attributes  \
2  ["Bikini-style panty in sheer lace ", " Featur...   
3  ["Bikini-style panty in sheer lace ", " Featur...   

                 total_sizes             available_size        color  \
2  ["Select", "S", "M", "L"]  ["Select", "S", "M", "L"]        Black   
3  ["Select", "S", "M", "L"]  ["Select", "S", "M", "L"]  Light Ivory   

  parent_category  
2         Panties  
3         Panties

In [384]:
macy_df.head(2)

product_name   mrp  price  \
8  Embrace Lace Contour Bra 853191  60.0   60.0   
9  Embrace Lace Contour Bra 853191  60.0   60.0   

                                             pdp_url brand_name  \
8  http://www1.macys.com/shop/product/wacoal-embr...     Wacoal   
9  http://www1.macys.com/shop/product/wacoal-embr...     Wacoal   

                      product_category  retailer  \
8  Women - Lingerie & Shapewear - Bras  Macys US   
9  Women - Lingerie & Shapewear - Bras  Macys US   

                                         description  rating  review_count  \
8  The latest style from Wacoal's popular Embrace...     4.5          75.0   
9  The latest style from Wacoal's popular Embrace...     4.5          75.0   

                                    style_attributes  \
8  ["Adjustable straps with scalloped edges", "Se...   
9  ["Adjustable straps with scalloped edges", "Se...   

                                         total_sizes  \
8  ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...   
9  ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...   

                                      available_size                 color  \
8  ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...                 Black   
9  ["30D", "30DD", "30DDD", "32C", "32D", "32DD",...  Naturally Nude/Ivory   

  parent_category  
8            Bras  
9            Bras

In [385]:
nord_df.head(2)

product_name   mrp  price  \
0  'B Fitting' High Cut Briefs  15.0   15.0   
1  'B Fitting' High Cut Briefs  15.0   15.0   

                                             pdp_url brand_name  \
0  http://shop.nordstrom.com/s/wacoal-b-fitting-h...     WACOAL   
1  http://shop.nordstrom.com/s/wacoal-b-fitting-h...     WACOAL   

  product_category      retailer  \
0  Women's Panties  Nordstrom US   
1  Women's Panties  Nordstrom US   

                                         description  rating  review_count  \
0  Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   
1  Lighter-than-air, full-cut Supima® cotton brie...     4.2          65.0   

                                    style_attributes total_sizes  \
0  ["79% Supima® cotton, 21% spandex.", "Hand was...       [nil]   
1  ["79% Supima® cotton, 21% spandex.", "Hand was...       [nil]   

  available_size  color parent_category  
0          [nil]  Black         Panties  
1          [nil]   Nude         Panties

In [386]:
frames = [ae_df, amz_df, btd_df, ck_df, hankypanky_df, macy_df, nord_df]

df = pd.concat(frames)

df.head()

product_name   mrp  price  \
0  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
1  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
2  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
3  Aerie Everyday Loves Lace Cheeky  12.5   12.5   
4  Aerie Everyday Loves Lace Cheeky  12.5   12.5   

                                             pdp_url brand_name  \
0  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
1  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
2  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
3  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   
4  https://www.ae.com/aerie-everyday-loves-lace-c...      AERIE   

  product_category retailer  \
0         Cheekies    Ae US   
1         Cheekies    Ae US   
2         Cheekies    Ae US   
3         Cheekies    Ae US   
4         Cheekies    Ae US   

                                         description  rating  review_count  \
0  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
1  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
2  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
3  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   
4  Introducing Everyday Loves™: Made with love. E...     5.0           8.0   

                                    style_attributes  \
0  ["Soft lace with the right amount of stretch",...   
1  ["Soft lace with the right amount of stretch",...   
2  ["Soft lace with the right amount of stretch",...   
3  ["Soft lace with the right amount of stretch",...   
4  ["Soft lace with the right amount of stretch",...   

                          total_sizes                      available_size  \
0  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
1  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
2  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
3  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   
4  ["XS", "S", "M", "L", "XL", "XXL"]  ["XS", "S", "M", "L", "XL", "XXL"]   

          color parent_category  
0  Rugged Green         Panties  
1  Natural Nude         Panties  
2    True Black         Panties  
3         White         Panties  
4    Royal Navy         Panties

In [387]:
df.tail()

product_name   mrp  price  \
12541             'Bodysuede' Lace Waist Briefs  18.0  18.00   
12556                               Lace Bikini  30.0  17.98   
12557         Modern Cotton Collection Bralette  28.0  16.80   
12566  Basic Benefits Full Figure Underwire Bra  55.0  55.00   
12567              Plunge Underwire Push-Up Bra  42.0  42.00   

                                                 pdp_url    brand_name  \
12541  http://shop.nordstrom.com/s/wacoal-bodysuede-l...        WACOAL   
12556  http://shop.nordstrom.com/s/hanky-panky-lace-b...   HANKY PANKY   
12557  http://shop.nordstrom.com/s/calvin-klein-moder...  CALVIN KLEIN   
12566  http://shop.nordstrom.com/s/wacoal-basic-benef...        WACOAL   
12567  http://shop.nordstrom.com/s/calvin-klein-plung...  CALVIN KLEIN   

      product_category      retailer  \
12541  Women's Panties  Nordstrom US   
12556  Women's Panties  Nordstrom US   
12557             Bras  Nordstrom US   
12566             Bras  Nordstrom US   
12567             Bras  Nordstrom US   

                                             description  rating  \
12541  A lacy waistband romances full-cut briefs with...     4.5   
12556  Classic bikini styling in a favorite fabricati...     5.0   
12557  A stretchy racerback bralette stamped in logos...     4.3   
12566  Beautiful ombré lace veils the cups of a full-...     4.3   
12567  Padded push-up cups enhance your figure in thi...     4.3   

       review_count                                   style_attributes  \
12541          26.0  ["78% nylon, 22% spandex; hand wash warm, line...   
12556           1.0  ["Cotton gusset.", "100% nylon.", "Hand wash c...   
12557           0.0  ["Slips on over head", "Partially lined", "53%...   
12566           0.0  ["Three-part cups offer moderate coverage and ...   
12567           0.0  ["Convertible straps", "Built-up side wing hei...   

                                             total_sizes  \
12541                    ["5", "6", "7", "8", "9", "10"]   
12556            ["Small", "X-Small", "Large", "Medium"]   
12557                       ["Small", "Medium", "Large"]   
12566  ["32D", "34D", "34DD", "42DDD", "34C", "36D", ...   
12567  ["32D", "34A", "34DD", "36B", "36C", "36D", "3...   

                                          available_size  \
12541                    ["10", "5", "7", "8", "9", "6"]   
12556            ["Small", "X-Small", "Large", "Medium"]   
12557                       ["Small", "Medium", "Large"]   
12566  ["32D", "34D", "34DD", "42DDD", "34C", "36D", ...   
12567  ["32D", "34A", "34DD", "36B", "36C", "36D", "3...   

                      color parent_category  
12541                 Ivory         Panties  
12556              Hyacinth         Panties  
12557           Random Logo            Bras  
12566  Navy Peony/ Infinity            Bras  
12567               Bronzed            Bras

In [388]:
df.to_csv('final.csv', index=False, encoding='utf-8-sig')